# Generated by ruby/codegen/generate.rb from the generator view. DO NOT EDIT.

require "json"

module Lingara
  module Events
    # The envelope's fields, in the order every arm holds them.
    ENVELOPE = %i[id type created_at api_version subject data].freeze

    # One outbound event. Every arm, UnknownEvent included, is an Event, so
    # `case event in Lingara::Events::Event` matches any of them.
    module Event
    end

    # lesson_plan.ready: data is a Lingara::LessonPlanReadyData.
    LessonPlanReady = Data.define(*ENVELOPE) { include Event }

    # lesson_plan.failed: data is a Lingara::LessonPlanFailedData.
    LessonPlanFailed = Data.define(*ENVELOPE) { include Event }

    # usage.threshold_reached: data is a Lingara::UsageThresholdReachedData.
    UsageThresholdReached = Data.define(*ENVELOPE) { include Event }

    # webhook.test: data is a Hash.
    WebhookTest = Data.define(*ENVELOPE) { include Event }

    # app.installed: data is a Lingara::AppInstalledData.
    AppInstalled = Data.define(*ENVELOPE) { include Event }

    # app.uninstalled: data is a Lingara::AppUninstalledData.
    AppUninstalled = Data.define(*ENVELOPE) { include Event }

    # app.disabled: data is a Lingara::AppDisabledData.
    AppDisabled = Data.define(*ENVELOPE) { include Event }

    # app.enabled: data is a Lingara::AppEnabledData.
    AppEnabled = Data.define(*ENVELOPE) { include Event }

    # practice.completed: data is a Lingara::PracticeCompletedData.
    PracticeCompleted = Data.define(*ENVELOPE) { include Event }

    # An event of a type this library does not know: data is the raw JSON
    # object, as a Hash. The catalogue only grows, so acknowledge it.
    UnknownEvent = Data.define(*ENVELOPE) { include Event }

    module Event
      # Each known type's arm and the name of its data model (nil: a Hash).
      ARMS = {
        "lesson_plan.ready" => [LessonPlanReady, "LessonPlanReadyData"].freeze,
        "lesson_plan.failed" => [LessonPlanFailed, "LessonPlanFailedData"].freeze,
        "usage.threshold_reached" => [UsageThresholdReached, "UsageThresholdReachedData"].freeze,
        "webhook.test" => [WebhookTest, nil].freeze,
        "app.installed" => [AppInstalled, "AppInstalledData"].freeze,
        "app.uninstalled" => [AppUninstalled, "AppUninstalledData"].freeze,
        "app.disabled" => [AppDisabled, "AppDisabledData"].freeze,
        "app.enabled" => [AppEnabled, "AppEnabledData"].freeze,
        "practice.completed" => [PracticeCompleted, "PracticeCompletedData"].freeze
      }.freeze
    end

    # An event a client sends with send_event: one constructor per inbound
    # type, each taking its data model. It serialises as {type, data}; the
    # server assigns the rest.
    class InboundEvent
      # Each inbound type's constructor.
      CONSTRUCTORS = {
        "world.context_changed" => :world_context_changed,
        "world.practice_requested" => :world_practice_requested,
        "world.practice_completed" => :world_practice_completed
      }.freeze

      attr_reader :type, :data

      private_class_method :new

      # world.context_changed, from a Lingara::WorldContextChanged or the Hash one is built from.
      def self.world_context_changed(data)
        new("world.context_changed", data.is_a?(Lingara::WorldContextChanged) ? data : Lingara::WorldContextChanged.new(data))
      end

      # world.practice_requested, from a Lingara::WorldPracticeRequested or the Hash one is built from.
      def self.world_practice_requested(data)
        new("world.practice_requested", data.is_a?(Lingara::WorldPracticeRequested) ? data : Lingara::WorldPracticeRequested.new(data))
      end

      # world.practice_completed, from a Lingara::WorldPracticeCompleted or the Hash one is built from.
      def self.world_practice_completed(data)
        new("world.practice_completed", data.is_a?(Lingara::WorldPracticeCompleted) ? data : Lingara::WorldPracticeCompleted.new(data))
      end

      def initialize(type, data)
        @type = type
        @data = data
        freeze
      end

      def to_hash
        {"type" => @type, "data" => @data.to_hash}
      end
    end

    # The Event for one envelope's JSON text: its arm for a known type, or
    # UnknownEvent. Text that is not an envelope, or a known type whose data
    # its model refuses, raises TransportError :malformed_event.
    def self.parse(json)
      decode(JSON.parse(json))
    rescue JSON::ParserError
      raise Lingara::TransportError.new(:malformed_event, "an event is not JSON")
    end

    # The same, from an envelope already parsed into a Hash.
    def self.decode(fields)
      raise Lingara::TransportError.new(:malformed_event, "an event is not a JSON object") unless fields.is_a?(Hash)
      envelope = Lingara::EventEnvelope.build_from_hash(fields)
      arm, model = Event::ARMS.fetch(envelope.type, [UnknownEvent, nil])
      data = model ? Lingara.const_get(model).build_from_hash(envelope.data) : envelope.data
      arm.new(id: envelope.id, type: envelope.type, created_at: envelope.created_at, api_version: envelope.api_version,
        subject: envelope.subject, data: data)
    rescue Lingara::Error
      raise
    rescue
      raise Lingara::TransportError.new(:malformed_event, "an event does not decode")
    end
  end
end
