<?php

declare(strict_types=1);

// php/codegen/generate.php: the half of the PHP library openapi-generator
// does not write (ADR 29.9.26u D2). It reads the generator view
// (spec/generator/openapi.3.0.json) and VERSION, and writes into php/src/
// (or --out <dir>):
//
//   Stream/<Union>.php            one marker interface per stream union
//   Stream/<Union>/<Event>.php    one final readonly class per event a stream
//                                 yields, holding the branch's `data` model
//   Internal/Operations.php       the nine routes keyed by operationId, each
//                                 stream's events and terminal table (from the
//                                 view's endsOn, ADR 29.9.26ai), and decode()
//   Version.php                   VERSION and GENERATED_FOR_VERSION
//
// It refuses a Model/ directory beside its output holding a file named after
// a union or one of its branches: codegen/php.openapi-generator-ignore names
// the four unions by glob, and a fifth stream it does not name would
// otherwise ship two types for one union. It also refuses an event whose
// class name would be a PHP reserved word. Standard library only; not in the
// dist.

const HEADER = "// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.";

// PHP class names are case-insensitive, so these are refused however an
// event name capitalises them.
const RESERVED = [
    'abstract', 'and', 'array', 'as', 'bool', 'break', 'callable', 'case', 'catch', 'class', 'clone', 'const',
    'continue', 'declare', 'default', 'do', 'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor',
    'endforeach', 'endif', 'endswitch', 'endwhile', 'enum', 'eval', 'exit', 'extends', 'false', 'final',
    'finally', 'float', 'fn', 'for', 'foreach', 'function', 'global', 'goto', 'if', 'implements', 'include',
    'instanceof', 'insteadof', 'int', 'interface', 'isset', 'iterable', 'list', 'match', 'mixed', 'namespace',
    'never', 'new', 'null', 'object', 'or', 'parent', 'print', 'private', 'protected', 'public', 'readonly',
    'require', 'resource', 'return', 'self', 'static', 'string', 'switch', 'throw', 'trait', 'true', 'try',
    'unset', 'use', 'var', 'void', 'while', 'xor', 'yield',
];

function fail(string $message): never
{
    fwrite(STDERR, "generate.php: {$message}\n");
    exit(1);
}

function refName(?string $ref): ?string
{
    if ($ref === null) {
        return null;
    }
    $parts = explode('/', $ref);
    return end($parts);
}

function pascal(string $name): string
{
    return str_replace(' ', '', ucwords(str_replace(['_', '-', '.'], ' ', $name)));
}

/** @return list<string> */
function pathParams(string $path): array
{
    preg_match_all('/\{([^}]+)\}/', $path, $m);
    return $m[1];
}

/**
 * One operation per `paths` entry and one per x-lingara-streams entry, sorted
 * by operationId so the output never depends on key order.
 *
 * @return array<string, array<string, mixed>>
 */
function operations(array $view): array
{
    $ops = [];
    foreach ($view['paths'] ?? [] as $path => $item) {
        foreach ($item as $method => $op) {
            if (!is_array($op) || !isset($op['operationId'])) {
                continue;
            }
            $schema = $op['responses']['200']['content']['application/json']['schema'] ?? null;
            $ops[$op['operationId']] = [
                'method' => strtoupper($method),
                'path' => $path,
                'pathParams' => pathParams($path),
                'needsToken' => ($op['security'] ?? []) !== [],
                'request' => refName($op['requestBody']['content']['application/json']['schema']['$ref'] ?? null),
                'response' => refName($schema['$ref'] ?? null),
                'stream' => null,
            ];
        }
    }
    foreach ($view['x-lingara-streams'] ?? [] as $entry) {
        $ops[$entry['operationId']] = streamOperation($view, $entry);
    }
    ksort($ops, SORT_STRING);
    return $ops;
}

/** @return array<string, mixed> */
function streamOperation(array $view, array $entry): array
{
    $id = $entry['operationId'];
    $union = $entry['union'];
    $mapping = $view['components']['schemas'][$union]['discriminator']['mapping']
        ?? fail("{$union} has no discriminator mapping in the view");
    $endsOn = $entry['endsOn'] ?? fail("{$id}: no endsOn; the view predates ADR 29.9.26ai");
    $events = [];
    foreach ($entry['events'] as $name) {
        $branch = refName($mapping[$name] ?? null) ?? fail("{$union} has no branch for {$name}");
        $data = refName($view['components']['schemas'][$branch]['properties']['data']['$ref'] ?? null)
            ?? fail("{$branch} has no data \$ref");
        $events[$name] = ['branch' => $branch, 'data' => $data, 'end' => ending($entry, $name, $data, $endsOn)];
    }
    foreach ($endsOn as $name) {
        isset($events[$name]) || fail("{$id}: endsOn names unknown event {$name}");
    }
    return [
        'method' => strtoupper($entry['method']),
        'path' => $entry['path'],
        'pathParams' => pathParams($entry['path']),
        'needsToken' => ($entry['scopes'] ?? []) !== [],
        'request' => refName($entry['requestBody'] ?? null),
        'response' => null,
        'stream' => ['union' => $union, 'events' => $events],
    ];
}

/**
 * CONTRACT.md K5's rule over endsOn (ADR 29.9.26ai): the entry's error event
 * raises, an ending event whose data is `Done` ends quietly, and any other
 * ending event is yielded and then ends the stream. An event that does not
 * end the stream is null.
 *
 * @param list<string> $endsOn
 */
function ending(array $entry, string $name, string $data, array $endsOn): ?string
{
    if (!in_array($name, $endsOn, true)) {
        return null;
    }
    if ($name === ($entry['error'] ?? null)) {
        return 'raise';
    }
    return $data === 'Done' ? 'quiet' : 'yield';
}

/** Whether a stream yields an event: never its error event, never a Done. */
function yielded(array $event): bool
{
    return $event['end'] !== 'raise' && $event['end'] !== 'quiet';
}

function eventClass(string $name): string
{
    $class = pascal($name);
    if (in_array(strtolower($class), RESERVED, true)) {
        fail("the event {$name} would be the class {$class}, a PHP reserved word");
    }
    return $class;
}

function export(mixed $value): string
{
    return match (true) {
        $value === null => 'null',
        is_bool($value) => $value ? 'true' : 'false',
        default => var_export($value, true),
    };
}

function operationsPhp(array $ops): string
{
    $rows = [];
    foreach ($ops as $id => $op) {
        $rows[] = '        ' . export($id) . " => [\n" . operationFields($op) . '        ],';
    }
    $table = implode("\n", $rows);
    $header = HEADER;
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Internal;

        use Lingara\\Exception\\TransportException;
        use Lingara\\Exception\\TransportKind;
        use Lingara\\ObjectSerializer;

        /**
         * Every operation's route, keyed by operationId: from `paths` for a JSON
         * operation and from `x-lingara-streams` for a stream. A stream's events
         * are in source order; each has its class (null when it is never
         * yielded), its `data` model and its end: 'yield' (yielded, then the
         * stream ends), 'quiet' (a Done payload, never yielded), 'raise' (the
         * error event) or null (the stream goes on).
         *
         * @internal
         */
        final class Operations
        {
            public const OPERATIONS = [
        {$table}
            ];

            /**
             * The event object for a known, yielded event name, or null for an
             * unknown one. \$data is the frame's `data` decoded as objects.
             *
             * @throws TransportException MalformedEvent when a known event's data
             *                            is not a JSON object or does not decode
             */
            public static function decode(string \$operationId, string \$name, mixed \$data): ?object
            {
                \$event = self::OPERATIONS[\$operationId]['stream']['events'][\$name] ?? null;
                if (\$event === null || \$event['class'] === null) {
                    return null;
                }
                if (!\$data instanceof \\stdClass) {
                    throw new TransportException(TransportKind::MalformedEvent, "{\$name}: data is not a JSON object");
                }
                try {
                    return new \$event['class'](ObjectSerializer::deserialize(\$data, \$event['data']));
                } catch (\\Throwable) {
                    throw new TransportException(TransportKind::MalformedEvent, "{\$name}: data does not decode");
                }
            }
        }

        PHP;
}

function operationFields(array $op): string
{
    $fields = [
        "'method' => " . export($op['method']),
        "'path' => " . export($op['path']),
        "'pathParams' => [" . implode(', ', array_map('export', $op['pathParams'])) . ']',
        "'needsToken' => " . export($op['needsToken']),
        "'request' => " . modelClass($op['request']),
        "'response' => " . modelClass($op['response']),
    ];
    $stream = $op['stream'];
    if ($stream === null) {
        $fields[] = "'stream' => null";
    } else {
        $union = $stream['union'];
        $events = [];
        foreach ($stream['events'] as $name => $event) {
            $class = yielded($event) ? "\\Lingara\\Stream\\{$union}\\" . eventClass($name) . '::class' : 'null';
            // A Done payload is a free-form object openapi-generator writes no
            // model for, and is never decoded.
            $data = $event['end'] === 'quiet' ? 'null' : modelClass($event['data']);
            $events[] = '                    ' . export($name) . " => ['class' => {$class}, 'data' => {$data}, 'end' => "
                . export($event['end']) . '],';
        }
        $fields[] = "'stream' => [\n                'union' => \\Lingara\\Stream\\{$union}::class,\n"
            . "                'events' => [\n" . implode("\n", $events) . "\n                ],\n            ]";
    }
    return implode('', array_map(static fn (string $f): string => "            {$f},\n", $fields));
}

function modelClass(?string $name): string
{
    return $name === null ? 'null' : "\\Lingara\\Model\\{$name}::class";
}

function unionPhp(string $operationId, string $union): string
{
    $header = HEADER;
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Stream;

        /**
         * One event of {$operationId}'s stream: every event class under
         * Lingara\\Stream\\{$union}\\ implements it, so `instanceof` against this
         * interface or one class is the whole of matching. The error event, and
         * a Done-bodied one, are never yielded.
         */
        interface {$union}
        {
        }

        PHP;
}

function eventPhp(string $union, string $name, string $class, string $data): string
{
    $header = HEADER;
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara\\Stream\\{$union};

        /** The `{$name}` event: its payload is `\$data`. */
        final readonly class {$class} implements \\Lingara\\Stream\\{$union}
        {
            // Fully qualified: an event may share its short name with its
            // payload's model (`notice` carries a Notice).
            public function __construct(public \\Lingara\\Model\\{$data} \$data)
            {
            }
        }

        PHP;
}

function versionPhp(string $version, string $generatedFor): string
{
    $header = HEADER;
    $v = export($version);
    $g = export($generatedFor);
    return <<<PHP
        <?php

        {$header}

        declare(strict_types=1);

        namespace Lingara;

        final class Version
        {
            /** This library's released version, SemVer, sent in every User-Agent (K6). */
            public const VERSION = {$v};

            /**
             * The /v1 version this library's models were generated from. A response
             * served under another version logs one warning per version id.
             */
            public const GENERATED_FOR_VERSION = {$g};
        }

        PHP;
}

function refuseGeneratedUnions(string $out, array $ops): void
{
    foreach ($ops as $op) {
        if ($op['stream'] === null) {
            continue;
        }
        $union = $op['stream']['union'];
        $names = [$union];
        foreach ($op['stream']['events'] as $event) {
            $names[] = $event['branch'];
        }
        foreach ($names as $name) {
            $file = "{$out}/Model/{$name}.php";
            if (file_exists($file)) {
                fail("{$file} is openapi-generator's copy of {$name}, part of the union {$union}; "
                    . 'name it in codegen/php.openapi-generator-ignore');
            }
        }
    }
}

/** @return array<string, string> relative path => contents */
function files(array $view, string $version): array
{
    $ops = operations($view);
    $files = [
        'Internal/Operations.php' => operationsPhp($ops),
        'Version.php' => versionPhp($version, (string) ($view['info']['version'] ?? '')),
    ];
    foreach ($ops as $id => $op) {
        if ($op['stream'] === null) {
            continue;
        }
        $union = $op['stream']['union'];
        $files["Stream/{$union}.php"] = unionPhp($id, $union);
        foreach ($op['stream']['events'] as $name => $event) {
            if (yielded($event)) {
                $class = eventClass($name);
                $files["Stream/{$union}/{$class}.php"] = eventPhp($union, $name, $class, $event['data']);
            }
        }
    }
    ksort($files, SORT_STRING);
    return $files;
}

function main(array $argv): void
{
    $root = dirname(__DIR__, 2);
    $options = getopt('', ['out:', 'view:', 'version:']);
    $out = rtrim((string) ($options['out'] ?? "{$root}/php/src"), '/');
    $viewFile = (string) ($options['view'] ?? "{$root}/spec/generator/openapi.3.0.json");
    $versionFile = (string) ($options['version'] ?? "{$root}/VERSION");
    try {
        $view = json_decode((string) file_get_contents($viewFile), true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $e) {
        fail("{$viewFile}: {$e->getMessage()}");
    }
    $version = trim((string) file_get_contents($versionFile));
    $ops = operations($view);
    refuseGeneratedUnions($out, $ops);
    $files = files($view, $version);
    // A stream or event the view no longer has leaves no stale file behind.
    if (is_dir("{$out}/Stream")) {
        $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator("{$out}/Stream", FilesystemIterator::SKIP_DOTS));
        foreach ($it as $file) {
            $relative = substr($file->getPathname(), strlen($out) + 1);
            if (!isset($files[$relative])) {
                unlink($file->getPathname());
            }
        }
    }
    foreach ($files as $relative => $text) {
        $path = "{$out}/{$relative}";
        is_dir(dirname($path)) || mkdir(dirname($path), 0o777, true);
        file_put_contents($path, $text);
    }
}

main($argv);
