package com.getlingara.codegen;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Writes the event union from the view's {@code x-lingara-events} (ADR 30.9.26aa D3): {@code
 * Event}, a sealed interface with one record per outbound entry and {@code UnknownEvent}; {@code
 * InboundEvent}, one constructor per inbound entry; and the parser behind {@code Event.parse}.
 *
 * <p>It runs after openapi-generator and StreamsCodegen in the same staging directory, and refuses,
 * naming the file, when openapi-generator wrote a model named after an {@code Event} arm: the
 * ignore files are static, so a new arm would otherwise ship two types for one name. The data
 * schemas themselves are never excluded, since the generated models are the arms' {@code data}.
 *
 * <p>Usage: {@code EventsCodegen <view> <staged sources>}, or {@code EventsCodegen --kotlin <view>
 * <staged sources>}.
 */
public final class EventsCodegen {
  static final String JAVA_PACKAGE = StreamsCodegen.BASE + ".events";
  static final String KOTLIN_PACKAGE = KotlinSource.BASE + ".events";
  static final String HEADER =
      "// Generated by :codegen's EventsCodegen from spec/generator/openapi.3.0.json."
          + " Do not edit.\n";

  private final JsonNode view;
  private final Path sources;
  private final StreamsCodegen.Lang lang;

  /**
   * One {@code x-lingara-events} entry.
   *
   * @param type the wire type, such as {@code lesson_plan.ready}
   * @param arm the outbound arm's name, or null for an inbound entry
   * @param data the data component's name
   */
  record Entry(String type, String arm, String data) {
    /** Whether Lingara sends it: an {@code Event} arm rather than an {@code InboundEvent}. */
    boolean outbound() {
      return arm != null;
    }
  }

  EventsCodegen(JsonNode view, Path sources, StreamsCodegen.Lang lang) {
    this.view = view;
    this.sources = sources;
    this.lang = lang;
  }

  /**
   * Runs the generator.
   *
   * @param args {@code [--kotlin] <view> <staged sources>}
   * @throws IOException when a file cannot be read or written
   */
  public static void main(String[] args) throws IOException {
    boolean kotlin = args.length == 3 && args[0].equals("--kotlin");
    if (args.length != 2 && !kotlin) {
      throw new IllegalArgumentException(
          "usage: EventsCodegen [--kotlin] <view> <staged sources>");
    }
    int at = kotlin ? 1 : 0;
    JsonNode view = new ObjectMapper().readTree(Path.of(args[at]).toFile());
    StreamsCodegen.Lang lang = kotlin ? StreamsCodegen.Lang.KOTLIN : StreamsCodegen.Lang.JAVA;
    new EventsCodegen(view, Path.of(args[at + 1]), lang).write();
  }

  /** Every entry, in the view's (document) order. */
  List<Entry> entries() {
    List<Entry> out = new ArrayList<>();
    for (JsonNode e : view.path("x-lingara-events")) {
      String arm = e.path("direction").asText().equals("out") ? e.path("arm").asText() : null;
      String data = StreamsCodegen.refName(e.path("data").asText());
      out.add(new Entry(e.path("type").asText(), arm, data));
    }
    return out;
  }

  /** Refuses a staged model named after an arm, then writes every file for the language. */
  void write() throws IOException {
    List<Entry> entries = entries();
    refuseGeneratorCopies(entries);
    if (lang == StreamsCodegen.Lang.KOTLIN) {
      Path dir = sources.resolve(StreamsCodegen.packagePath(KOTLIN_PACKAGE));
      for (KotlinEventsSource.File f : KotlinEventsSource.files(entries, this::dataClass)) {
        StreamsCodegen.writeFile(dir.resolve(f.name()), f.text());
      }
      return;
    }
    Path dir = sources.resolve(StreamsCodegen.packagePath(JAVA_PACKAGE));
    for (JavaEventsSource.File f : JavaEventsSource.files(entries, this::dataClass)) {
      StreamsCodegen.writeFile(dir.resolve(f.name()), f.text());
    }
  }

  void refuseGeneratorCopies(List<Entry> entries) {
    Path models = sources.resolve(StreamsCodegen.packagePath(lang.model()));
    List<String> names = new ArrayList<>(List.of("Event", "UnknownEvent", "InboundEvent"));
    entries.stream().filter(Entry::outbound).forEach(e -> names.add(e.arm()));
    for (String name : names) {
      Path file = models.resolve(name + lang.extension());
      if (Files.exists(file)) {
        throw new IllegalStateException(
            file
                + " was written by openapi-generator, but "
                + name
                + " is an event union type (ADR 30.9.26aa D3): add a glob for it to codegen/"
                + lang.ignoreFile()
                + ".openapi-generator-ignore");
      }
    }
  }

  /**
   * The class a data schema decodes into: the generated model when openapi-generator wrote one, and
   * the language's JSON tree for a free-form object, such as {@code WebhookTestData}.
   */
  String dataClass(String schema) {
    Path models = sources.resolve(StreamsCodegen.packagePath(lang.model()));
    return Files.exists(models.resolve(schema + lang.extension()))
        ? lang.model() + "." + schema
        : lang.freeForm();
  }
}
