package com.getlingara.codegen;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Writes what openapi-generator does not: each stream's union as a sealed interface of records,
 * {@code internal.Streams} (routes, event names, the terminal table and a decoder per stream),
 * {@code internal.SpecVersion} and {@code version.properties} (ADR 29.9.26r D3).
 *
 * <p>It reads {@code x-lingara-streams} and the branch components from the same generator view
 * openapi-generator reads, and runs after it in the same staging directory. It refuses, naming the
 * file, when openapi-generator wrote a file named after a union or a branch: a fifth stream the
 * ignore file does not name then fails {@code generateJava} instead of shipping two types for one
 * union.
 *
 * <p>Its Kotlin emitter (ADR 29.9.26s D2) writes the same unions as sealed interfaces of {@code
 * Serializable} data classes, {@code internal.Streams} as an internal object, and {@code
 * internal.BuildInfo}, from the same reading of the view, so the two languages' unions cannot read
 * it differently.
 *
 * <p>Usage: {@code StreamsCodegen <view> <VERSION> <staged sources> <staged resources>}, or {@code
 * StreamsCodegen --kotlin <view> <VERSION> <staged sources>}.
 */
public final class StreamsCodegen {
  static final String BASE = "com.getlingara.client";
  static final String MODEL = BASE + ".model";
  static final String HEADER =
      "// Generated by :codegen's StreamsCodegen from spec/generator/openapi.3.0.json."
          + " Do not edit.\n";

  private final JsonNode view;
  private final Path sources;
  private final Lang lang;

  /**
   * What differs between the Java and Kotlin output: the model package, the file extension, the
   * type a payload with no generated model decodes into, and the ignore file a refusal names.
   */
  record Lang(String model, String extension, String freeForm, String ignoreFile) {
    static final Lang JAVA =
        new Lang(MODEL, ".java", "com.fasterxml.jackson.databind.JsonNode", "java");
    static final Lang KOTLIN =
        new Lang(KotlinSource.MODEL, ".kt", "kotlinx.serialization.json.JsonElement", "kotlin");
  }

  /** One stream operation, as {@code x-lingara-streams} and its union describe it. */
  record Stream(
      String operationId,
      String method,
      String path,
      String requestBody,
      List<String> pathParameters,
      String union,
      List<Event> events) {}

  /** One event of a stream: its name, branch component, payload schema and how it ends. */
  record Event(String name, String branch, String data, Ending ending) {
    /** Whether the union has a member for this event: never the error, never a quiet end. */
    boolean yielded() {
      return ending == Ending.NONE || ending == Ending.YIELD;
    }
  }

  /** What an event does to iteration (CONTRACT.md K5's rule, ADR 29.9.26ai). */
  enum Ending {
    NONE,
    YIELD,
    QUIET,
    RAISE
  }

  StreamsCodegen(JsonNode view, Path sources) {
    this(view, sources, Lang.JAVA);
  }

  StreamsCodegen(JsonNode view, Path sources, Lang lang) {
    this.view = view;
    this.sources = sources;
    this.lang = lang;
  }

  /**
   * Runs the generator.
   *
   * @param args the view, VERSION, the staged sources root and the staged resources root
   * @throws IOException when a file cannot be read or written
   */
  public static void main(String[] args) throws IOException {
    if (args.length == 4 && args[0].equals("--kotlin")) {
      JsonNode view = new ObjectMapper().readTree(Path.of(args[1]).toFile());
      String version = Files.readString(Path.of(args[2]), StandardCharsets.UTF_8).trim();
      new StreamsCodegen(view, Path.of(args[3]), Lang.KOTLIN).writeKotlin(version);
      return;
    }
    if (args.length != 4) {
      throw new IllegalArgumentException(
          "usage: StreamsCodegen <view> <VERSION> <staged sources> <staged resources>");
    }
    JsonNode view = new ObjectMapper().readTree(Path.of(args[0]).toFile());
    String version = Files.readString(Path.of(args[1]), StandardCharsets.UTF_8).trim();
    new StreamsCodegen(view, Path.of(args[2])).write(version, Path.of(args[3]));
  }

  /** Every stream in the view, in its order. */
  List<Stream> streams() {
    List<Stream> out = new ArrayList<>();
    for (JsonNode entry : view.path("x-lingara-streams")) {
      out.add(stream(entry));
    }
    return out;
  }

  /** Refuses a staged copy of any union or branch, then writes every file. */
  void write(String version, Path resources) throws IOException {
    List<Stream> streams = streams();
    refuseGeneratorCopies(streams);
    for (Stream s : streams) {
      writeFile(sources.resolve(packagePath(MODEL)).resolve(s.union() + ".java"), union(s));
    }
    Path internal = sources.resolve(packagePath(BASE + ".internal"));
    writeFile(internal.resolve("Streams.java"), StreamsSource.render(streams, this::dataClass));
    writeFile(internal.resolve("SpecVersion.java"), specVersion());
    writeFile(
        resources.resolve(packagePath(BASE)).resolve("version.properties"),
        "version=" + version + "\n");
  }

  /** The Kotlin output: refuses a staged copy of any union or branch, then writes every file. */
  void writeKotlin(String version) throws IOException {
    List<Stream> streams = streams();
    refuseGeneratorCopies(streams);
    for (Stream s : streams) {
      writeFile(
          sources.resolve(packagePath(lang.model())).resolve(s.union() + ".kt"),
          KotlinSource.union(s, this::dataClass));
    }
    Path internal = sources.resolve(packagePath(KotlinSource.BASE + ".internal"));
    writeFile(internal.resolve("Streams.kt"), KotlinSource.streams(streams, this::dataClass));
    String generatedFor = view.path("info").path("version").asText();
    writeFile(internal.resolve("BuildInfo.kt"), KotlinSource.buildInfo(version, generatedFor));
  }

  void refuseGeneratorCopies(List<Stream> streams) {
    Path models = sources.resolve(packagePath(lang.model()));
    for (Stream s : streams) {
      List<String> names = new ArrayList<>();
      names.add(s.union());
      s.events().forEach(e -> names.add(e.branch()));
      for (String name : names) {
        Path file = models.resolve(name + lang.extension());
        if (Files.exists(file)) {
          throw new IllegalStateException(
              file
                  + " was written by openapi-generator, but "
                  + name
                  + " belongs to the stream union "
                  + s.union()
                  + ": add a glob for it to codegen/"
                  + lang.ignoreFile()
                  + ".openapi-generator-ignore");
        }
      }
    }
  }

  private Stream stream(JsonNode entry) {
    String union = entry.path("union").asText();
    JsonNode mapping = schema(union).path("discriminator").path("mapping");
    List<String> endsOn = texts(entry.path("endsOn"));
    String error = entry.path("error").asText();
    List<Event> events = new ArrayList<>();
    for (String name : texts(entry.path("events"))) {
      String branch = refName(mapping.path(name).asText());
      String data = refName(schema(branch).path("properties").path("data").path("$ref").asText());
      events.add(new Event(name, branch, data, ending(name, data, endsOn, error)));
    }
    return new Stream(
        entry.path("operationId").asText(),
        entry.path("method").asText().toUpperCase(java.util.Locale.ROOT),
        entry.path("path").asText(),
        entry.path("requestBody").isNull() ? null : refName(entry.path("requestBody").asText()),
        pathParameters(entry.path("parameters")),
        union,
        events);
  }

  static Ending ending(String name, String data, List<String> endsOn, String error) {
    if (name.equals(error)) {
      return Ending.RAISE;
    }
    if (!endsOn.contains(name)) {
      return Ending.NONE;
    }
    return "Done".equals(data) ? Ending.QUIET : Ending.YIELD;
  }

  private List<String> pathParameters(JsonNode refs) {
    List<String> out = new ArrayList<>();
    for (JsonNode ref : refs) {
      JsonNode parameter = view.path("components").path("parameters").path(refName(ref.asText()));
      if ("path".equals(parameter.path("in").asText())) {
        out.add(parameter.path("name").asText());
      }
    }
    return out;
  }

  private JsonNode schema(String name) {
    JsonNode schema = view.path("components").path("schemas").path(name);
    if (schema.isMissingNode()) {
      throw new IllegalStateException("the view has no component schema " + name);
    }
    return schema;
  }

  /**
   * The class a payload decodes into: the generated model when openapi-generator wrote one, and the
   * language's JSON tree ({@code JsonNode}, {@code JsonElement}) for a schema it modelled as a
   * free-form object, such as {@code Done}.
   */
  String dataClass(String schema) {
    Path models = sources.resolve(packagePath(lang.model()));
    return Files.exists(models.resolve(schema + lang.extension()))
        ? lang.model() + "." + schema
        : lang.freeForm();
  }

  String union(Stream s) {
    StringBuilder b = new StringBuilder(HEADER);
    b.append("\npackage ").append(MODEL).append(";\n\n");
    b.append("/**\n * One event of {@code ").append(s.operationId()).append("}'s stream.\n *\n");
    b.append(" * <p>The error event is raised and a {@code Done}-bodied ending event ends the\n");
    b.append(" * stream unyielded, so neither has a member: a pattern match covers exactly what\n");
    b.append(" * the stream can yield.\n */\n");
    b.append("public sealed interface ").append(s.union()).append(" {\n");
    for (Event e : s.events()) {
      if (e.yielded()) {
        String member = pascal(e.name());
        b.append("\n  /** The {@code ").append(e.name()).append("} event. */\n");
        b.append("  record ").append(member).append('(').append(dataClass(e.data()));
        b.append(" data) implements ").append(s.union()).append(" {}\n");
      }
    }
    return b.append("}\n").toString();
  }

  String specVersion() {
    String version = view.path("info").path("version").asText();
    return HEADER
        + "\npackage "
        + BASE
        + ".internal;\n\n"
        + "/** The API version this library's models were generated from (ADR 30.9.26a). */\n"
        + "public final class SpecVersion {\n"
        + "  /** The view's {@code info.version}. */\n"
        + "  public static final String GENERATED_FOR_VERSION = \""
        + version
        + "\";\n\n"
        + "  private SpecVersion() {}\n"
        + "}\n";
  }

  static String pascal(String name) {
    StringBuilder b = new StringBuilder();
    boolean upper = true;
    for (char c : name.toCharArray()) {
      if (!Character.isLetterOrDigit(c)) {
        upper = true;
      } else {
        b.append(upper ? Character.toUpperCase(c) : c);
        upper = false;
      }
    }
    return b.toString();
  }

  static String refName(String ref) {
    return ref.substring(ref.lastIndexOf('/') + 1);
  }

  static List<String> texts(JsonNode array) {
    List<String> out = new ArrayList<>();
    array.forEach(n -> out.add(n.asText()));
    return out;
  }

  static String packagePath(String pkg) {
    return pkg.replace('.', '/');
  }

  static void writeFile(Path file, String text) throws IOException {
    Files.createDirectories(file.getParent());
    Files.writeString(file, text, StandardCharsets.UTF_8);
  }

  /** Streams.java's source, kept apart so each renderer stays one screen. */
  static final class StreamsSource {
    private StreamsSource() {}

    static String render(List<Stream> streams, java.util.function.UnaryOperator<String> classOf) {
      StringBuilder b = new StringBuilder(HEADER);
      b.append("\npackage ").append(BASE).append(".internal;\n\n");
      b.append("import com.fasterxml.jackson.databind.JsonNode;\n");
      b.append("import com.fasterxml.jackson.databind.ObjectMapper;\n");
      b.append("import java.io.IOException;\n");
      b.append("import java.util.List;\n");
      b.append("import java.util.Map;\n\n");
      b.append(PREAMBLE);
      for (Stream s : streams) {
        route(b, s, classOf);
      }
      routes(b, streams);
      for (Stream s : streams) {
        decoder(b, s, classOf);
      }
      return b.append("}\n").toString();
    }

    private static void route(
        StringBuilder b, Stream s, java.util.function.UnaryOperator<String> classOf) {
      b.append("\n  /** {@code ").append(s.operationId()).append("}. */\n");
      b.append("  public static final Route ").append(constant(s.operationId()));
      b.append(" =\n      new Route(\n");
      b.append("          \"").append(s.operationId()).append("\",\n");
      b.append("          \"").append(s.method()).append("\",\n");
      b.append("          \"").append(s.path()).append("\",\n");
      b.append("          ")
          .append(s.requestBody() == null ? "null" : MODEL + "." + s.requestBody() + ".class")
          .append(",\n");
      b.append("          List.of(").append(quoted(s.pathParameters())).append("),\n");
      List<String> names = new ArrayList<>();
      Map<String, String> ends = new LinkedHashMap<>();
      Map<String, String> types = new LinkedHashMap<>();
      for (Event e : s.events()) {
        names.add(e.name());
        types.put(e.name(), classOf.apply(e.data()) + ".class");
        if (e.ending() != Ending.NONE) {
          ends.put(e.name(), "Ending." + e.ending());
        }
      }
      b.append("          List.of(").append(quoted(names)).append("),\n");
      b.append("          Map.of(").append(entries(ends)).append("),\n");
      b.append("          Map.of(").append(entries(types)).append("));\n");
    }

    private static void routes(StringBuilder b, List<Stream> streams) {
      b.append("\n  /** Every stream route, by operationId. */\n");
      b.append("  public static final Map<String, Route> ROUTES =\n      Map.of(");
      List<String> pairs = new ArrayList<>();
      for (Stream s : streams) {
        pairs.add("\"" + s.operationId() + "\", " + constant(s.operationId()));
      }
      b.append(String.join(", ", pairs)).append(");\n");
    }

    private static void decoder(
        StringBuilder b, Stream s, java.util.function.UnaryOperator<String> classOf) {
      String union = MODEL + "." + s.union();
      b.append("\n  /**\n   * Decodes one {@code ").append(s.operationId());
      b.append("} event, or returns null for a name the union has\n");
      b.append("   * no member for.\n   */\n");
      b.append("  public static ").append(union).append(" decode").append(pascal(s.operationId()));
      b.append("(\n      String event, JsonNode data, ObjectMapper mapper) throws IOException {\n");
      b.append("    switch (event) {\n");
      for (Event e : s.events()) {
        if (e.yielded()) {
          b.append("      case \"").append(e.name()).append("\":\n");
          b.append("        return new ").append(union).append('.').append(pascal(e.name()));
          b.append("(mapper.treeToValue(data, ").append(classOf.apply(e.data()));
          b.append(".class));\n");
        }
      }
      b.append("      default:\n        return null;\n    }\n  }\n");
    }

    static String constant(String operationId) {
      return operationId
          .replaceAll("([a-z0-9])([A-Z])", "$1_$2")
          .toUpperCase(java.util.Locale.ROOT);
    }

    private static String quoted(List<String> values) {
      List<String> out = new ArrayList<>();
      values.forEach(v -> out.add("\"" + v + "\""));
      return String.join(", ", out);
    }

    private static String entries(Map<String, String> map) {
      List<String> out = new ArrayList<>();
      map.forEach((k, v) -> out.add("\"" + k + "\", " + v));
      return String.join(", ", out);
    }

    static final String PREAMBLE =
        "/**\n"
            + " * Each stream's route, event names, terminal table and payload types, from the\n"
            + " * view's {@code x-lingara-streams}, and a decoder per stream (ADR 29.9.26r D3,\n"
            + " * ADR 29.9.26ai).\n"
            + " */\n"
            + "public final class Streams {\n"
            + "  private Streams() {}\n\n"
            + "  /** What an ending event does to iteration (CONTRACT.md K5). */\n"
            + "  public enum Ending {\n"
            + "    /** Yielded, then the stream ends. */\n"
            + "    YIELD,\n"
            + "    /** A {@code Done} payload: the stream ends unyielded. */\n"
            + "    QUIET,\n"
            + "    /** The failure event: raised as an {@code ApiException} with status 200. */\n"
            + "    RAISE\n"
            + "  }\n\n"
            + "  /**\n"
            + "   * One stream operation.\n"
            + "   *\n"
            + "   * @param operationId the operationId\n"
            + "   * @param method the HTTP method\n"
            + "   * @param path the path template\n"
            + "   * @param requestBody the request body's model, or null\n"
            + "   * @param pathParameters the path parameters' names\n"
            + "   * @param events every event name, in source order\n"
            + "   * @param endsOn the ending events and what each does\n"
            + "   * @param dataTypes each event's payload type\n"
            + "   */\n"
            + "  public record Route(\n"
            + "      String operationId,\n"
            + "      String method,\n"
            + "      String path,\n"
            + "      Class<?> requestBody,\n"
            + "      List<String> pathParameters,\n"
            + "      List<String> events,\n"
            + "      Map<String, Ending> endsOn,\n"
            + "      Map<String, Class<?>> dataTypes) {}\n";
  }
}
