=begin
#Lingara API

#Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.

The version of the OpenAPI document: 2026-09-glowing-hoatzin

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Lingara
  class AllowanceRow
    attr_accessor :feature

    attr_accessor :window

    attr_accessor :limit

    attr_accessor :used

    attr_accessor :remaining

    attr_accessor :reset_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'feature' => :'feature',
        :'window' => :'window',
        :'limit' => :'limit',
        :'used' => :'used',
        :'remaining' => :'remaining',
        :'reset_at' => :'reset_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'feature' => :'String',
        :'window' => :'String',
        :'limit' => :'Integer',
        :'used' => :'Integer',
        :'remaining' => :'Integer',
        :'reset_at' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'reset_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lingara::AllowanceRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lingara::AllowanceRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'feature')
        self.feature = attributes[:'feature']
      else
        self.feature = nil
      end

      if attributes.key?(:'window')
        self.window = attributes[:'window']
      else
        self.window = nil
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      else
        self.limit = nil
      end

      if attributes.key?(:'used')
        self.used = attributes[:'used']
      else
        self.used = nil
      end

      if attributes.key?(:'remaining')
        self.remaining = attributes[:'remaining']
      else
        self.remaining = nil
      end

      if attributes.key?(:'reset_at')
        self.reset_at = attributes[:'reset_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @feature.nil?
        invalid_properties.push('invalid value for "feature", feature cannot be nil.')
      end

      if @window.nil?
        invalid_properties.push('invalid value for "window", window cannot be nil.')
      end

      if @limit.nil?
        invalid_properties.push('invalid value for "limit", limit cannot be nil.')
      end

      if @limit < 0
        invalid_properties.push('invalid value for "limit", must be greater than or equal to 0.')
      end

      if @used.nil?
        invalid_properties.push('invalid value for "used", used cannot be nil.')
      end

      if @used < 0
        invalid_properties.push('invalid value for "used", must be greater than or equal to 0.')
      end

      if @remaining.nil?
        invalid_properties.push('invalid value for "remaining", remaining cannot be nil.')
      end

      if @remaining < 0
        invalid_properties.push('invalid value for "remaining", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @feature.nil?
      return false if @window.nil?
      return false if @limit.nil?
      return false if @limit < 0
      return false if @used.nil?
      return false if @used < 0
      return false if @remaining.nil?
      return false if @remaining < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] feature Value to be assigned
    def feature=(feature)
      if feature.nil?
        fail ArgumentError, 'feature cannot be nil'
      end

      @feature = feature
    end

    # Custom attribute writer method with validation
    # @param [Object] window Value to be assigned
    def window=(window)
      if window.nil?
        fail ArgumentError, 'window cannot be nil'
      end

      @window = window
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)
      if limit.nil?
        fail ArgumentError, 'limit cannot be nil'
      end

      if limit < 0
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 0.'
      end

      @limit = limit
    end

    # Custom attribute writer method with validation
    # @param [Object] used Value to be assigned
    def used=(used)
      if used.nil?
        fail ArgumentError, 'used cannot be nil'
      end

      if used < 0
        fail ArgumentError, 'invalid value for "used", must be greater than or equal to 0.'
      end

      @used = used
    end

    # Custom attribute writer method with validation
    # @param [Object] remaining Value to be assigned
    def remaining=(remaining)
      if remaining.nil?
        fail ArgumentError, 'remaining cannot be nil'
      end

      if remaining < 0
        fail ArgumentError, 'invalid value for "remaining", must be greater than or equal to 0.'
      end

      @remaining = remaining
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          feature == o.feature &&
          window == o.window &&
          limit == o.limit &&
          used == o.used &&
          remaining == o.remaining &&
          reset_at == o.reset_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [feature, window, limit, used, remaining, reset_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Lingara.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
