=begin
#Lingara API

#Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.

The version of the OpenAPI document: 2026-09-glowing-hoatzin

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Lingara
  class LessonPlanContent
    attr_accessor :introduction

    attr_accessor :learning_objectives

    attr_accessor :vocabulary

    attr_accessor :sets

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'introduction' => :'introduction',
        :'learning_objectives' => :'learning_objectives',
        :'vocabulary' => :'vocabulary',
        :'sets' => :'sets'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'introduction' => :'String',
        :'learning_objectives' => :'Array<String>',
        :'vocabulary' => :'Array<PlanWord>',
        :'sets' => :'Array<PlanSet>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'introduction',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lingara::LessonPlanContent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lingara::LessonPlanContent`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'introduction')
        self.introduction = attributes[:'introduction']
      end

      if attributes.key?(:'learning_objectives')
        if (value = attributes[:'learning_objectives']).is_a?(Array)
          self.learning_objectives = value
        end
      else
        self.learning_objectives = nil
      end

      if attributes.key?(:'vocabulary')
        if (value = attributes[:'vocabulary']).is_a?(Array)
          self.vocabulary = value
        end
      else
        self.vocabulary = nil
      end

      if attributes.key?(:'sets')
        if (value = attributes[:'sets']).is_a?(Array)
          self.sets = value
        end
      else
        self.sets = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @learning_objectives.nil?
        invalid_properties.push('invalid value for "learning_objectives", learning_objectives cannot be nil.')
      end

      if @vocabulary.nil?
        invalid_properties.push('invalid value for "vocabulary", vocabulary cannot be nil.')
      end

      if @sets.nil?
        invalid_properties.push('invalid value for "sets", sets cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @learning_objectives.nil?
      return false if @vocabulary.nil?
      return false if @sets.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] learning_objectives Value to be assigned
    def learning_objectives=(learning_objectives)
      if learning_objectives.nil?
        fail ArgumentError, 'learning_objectives cannot be nil'
      end

      @learning_objectives = learning_objectives
    end

    # Custom attribute writer method with validation
    # @param [Object] vocabulary Value to be assigned
    def vocabulary=(vocabulary)
      if vocabulary.nil?
        fail ArgumentError, 'vocabulary cannot be nil'
      end

      @vocabulary = vocabulary
    end

    # Custom attribute writer method with validation
    # @param [Object] sets Value to be assigned
    def sets=(sets)
      if sets.nil?
        fail ArgumentError, 'sets cannot be nil'
      end

      @sets = sets
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          introduction == o.introduction &&
          learning_objectives == o.learning_objectives &&
          vocabulary == o.vocabulary &&
          sets == o.sets
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [introduction, learning_objectives, vocabulary, sets].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Lingara.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
