=begin
#Lingara API

#Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.

The version of the OpenAPI document: 2026-10-golden-remora

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Lingara
  class PlanStatus
    GENERATING = "generating".freeze
    PARTIAL = "partial".freeze
    COMPLETE = "complete".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [GENERATING, PARTIAL, COMPLETE, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PlanStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PlanStatus"
    end
  end
end
