=begin
#Lingara API

#Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.

The version of the OpenAPI document: 2026-09-glowing-hoatzin

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Lingara
  class VocabMeta
    attr_accessor :level

    attr_accessor :source_lang

    attr_accessor :target_lang

    attr_accessor :framework

    attr_accessor :count

    attr_accessor :ai_generated

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'level' => :'level',
        :'source_lang' => :'source_lang',
        :'target_lang' => :'target_lang',
        :'framework' => :'framework',
        :'count' => :'count',
        :'ai_generated' => :'ai_generated'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'level' => :'Integer',
        :'source_lang' => :'String',
        :'target_lang' => :'String',
        :'framework' => :'String',
        :'count' => :'Integer',
        :'ai_generated' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lingara::VocabMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lingara::VocabMeta`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'level')
        self.level = attributes[:'level']
      else
        self.level = nil
      end

      if attributes.key?(:'source_lang')
        self.source_lang = attributes[:'source_lang']
      else
        self.source_lang = nil
      end

      if attributes.key?(:'target_lang')
        self.target_lang = attributes[:'target_lang']
      else
        self.target_lang = nil
      end

      if attributes.key?(:'framework')
        self.framework = attributes[:'framework']
      else
        self.framework = nil
      end

      if attributes.key?(:'count')
        self.count = attributes[:'count']
      else
        self.count = nil
      end

      if attributes.key?(:'ai_generated')
        self.ai_generated = attributes[:'ai_generated']
      else
        self.ai_generated = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @level.nil?
        invalid_properties.push('invalid value for "level", level cannot be nil.')
      end

      if @level > 255
        invalid_properties.push('invalid value for "level", must be smaller than or equal to 255.')
      end

      if @level < 0
        invalid_properties.push('invalid value for "level", must be greater than or equal to 0.')
      end

      if @source_lang.nil?
        invalid_properties.push('invalid value for "source_lang", source_lang cannot be nil.')
      end

      if @target_lang.nil?
        invalid_properties.push('invalid value for "target_lang", target_lang cannot be nil.')
      end

      if @framework.nil?
        invalid_properties.push('invalid value for "framework", framework cannot be nil.')
      end

      if @count.nil?
        invalid_properties.push('invalid value for "count", count cannot be nil.')
      end

      if @count < 0
        invalid_properties.push('invalid value for "count", must be greater than or equal to 0.')
      end

      if @ai_generated.nil?
        invalid_properties.push('invalid value for "ai_generated", ai_generated cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @level.nil?
      return false if @level > 255
      return false if @level < 0
      return false if @source_lang.nil?
      return false if @target_lang.nil?
      return false if @framework.nil?
      return false if @count.nil?
      return false if @count < 0
      return false if @ai_generated.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] level Value to be assigned
    def level=(level)
      if level.nil?
        fail ArgumentError, 'level cannot be nil'
      end

      if level > 255
        fail ArgumentError, 'invalid value for "level", must be smaller than or equal to 255.'
      end

      if level < 0
        fail ArgumentError, 'invalid value for "level", must be greater than or equal to 0.'
      end

      @level = level
    end

    # Custom attribute writer method with validation
    # @param [Object] source_lang Value to be assigned
    def source_lang=(source_lang)
      if source_lang.nil?
        fail ArgumentError, 'source_lang cannot be nil'
      end

      @source_lang = source_lang
    end

    # Custom attribute writer method with validation
    # @param [Object] target_lang Value to be assigned
    def target_lang=(target_lang)
      if target_lang.nil?
        fail ArgumentError, 'target_lang cannot be nil'
      end

      @target_lang = target_lang
    end

    # Custom attribute writer method with validation
    # @param [Object] framework Value to be assigned
    def framework=(framework)
      if framework.nil?
        fail ArgumentError, 'framework cannot be nil'
      end

      @framework = framework
    end

    # Custom attribute writer method with validation
    # @param [Object] count Value to be assigned
    def count=(count)
      if count.nil?
        fail ArgumentError, 'count cannot be nil'
      end

      if count < 0
        fail ArgumentError, 'invalid value for "count", must be greater than or equal to 0.'
      end

      @count = count
    end

    # Custom attribute writer method with validation
    # @param [Object] ai_generated Value to be assigned
    def ai_generated=(ai_generated)
      if ai_generated.nil?
        fail ArgumentError, 'ai_generated cannot be nil'
      end

      @ai_generated = ai_generated
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          level == o.level &&
          source_lang == o.source_lang &&
          target_lang == o.target_lang &&
          framework == o.framework &&
          count == o.count &&
          ai_generated == o.ai_generated
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [level, source_lang, target_lang, framework, count, ai_generated].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Lingara.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
