<?php

// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.

declare(strict_types=1);

namespace Lingara\Stream\GenerateVocabularyEvent;

/** The `item` event: its payload is `$data`. */
final readonly class Item implements \Lingara\Stream\GenerateVocabularyEvent
{
    // Fully qualified: an event may share its short name with its
    // payload's model (`notice` carries a Notice).
    public function __construct(public \Lingara\Model\VocabItem $data)
    {
    }
}
