<?php

// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.

declare(strict_types=1);

namespace Lingara\Stream;

/**
 * One event of streamLessonPlan's stream: every event class under
 * Lingara\Stream\StreamLessonPlanEvent\ implements it, so `instanceof` against this
 * interface or one class is the whole of matching. The error event, and
 * a Done-bodied one, are never yielded.
 */
interface StreamLessonPlanEvent
{
}
