//! `lingara-xtask codegen`: writes `rust/src/generated/` from the generator
//! view (ADR 29.9.26p D2).
//!
//! - `models.rs` is typify over every `components.schemas` entry except the
//!   stream unions and their per-event branches;
//! - `streams.rs` is written here from `x-lingara-streams`, which typify does
//!   not read: one `#[serde(tag = "event", content = "data")]` enum per
//!   stream, and one route `const` per stream;
//! - `events.rs` is written here from `x-lingara-events` (ADR 30.9.26aa D3):
//!   the `Event` union, `UnknownEvent`, `InboundEvent` and `parse_event`. A
//!   component named after an `Event` arm is refused, not skipped;
//! - `mod.rs` allows clippy over all three.
//!
//! Everything is rendered through prettyplease, so two runs are
//! byte-identical. `--out-dir <dir>` writes elsewhere (the make check diffs a
//! temporary directory); `--check` compares with the committed files instead
//! of writing.

mod events;
mod streams;

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde_json::{Map, Value};
use typify::{TypeSpace, TypeSpaceSettings};

use streams::Stream;

const VIEW: &str = "spec/generator/openapi.3.1.json";
const OUT_DIR: &str = "rust/src/generated";
const HEADER: &str = "// Generated by lingara-xtask from spec/generator/openapi.3.1.json.\n\
                      // Do not edit: run `make codegen-rust`.\n\n";
const MOD_RS: &str = "#![allow(clippy::all)]\n\npub mod events;\npub mod models;\npub mod spec_version;\npub mod streams;\n";

/// The `format`s typify would map to `chrono` and `uuid` types. The crate
/// keeps the server's strings instead (D2), so they are removed from the
/// in-memory copy of the schemas; the committed view is untouched.
const STRING_FORMATS: [&str; 2] = ["date-time", "uuid"];

fn main() -> ExitCode {
    match run(std::env::args().skip(1).collect()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("✗ lingara-xtask: {message}");
            ExitCode::FAILURE
        }
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    let usage = "usage: lingara-xtask codegen [--check] [--out-dir <dir>]";
    let mut args = args.into_iter();
    if args.next().as_deref() != Some("codegen") {
        return Err(usage.into());
    }
    let root = workspace_root();
    let (mut check, mut out) = (false, root.join(OUT_DIR));
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--check" => check = true,
            "--out-dir" => out = PathBuf::from(args.next().ok_or(usage)?),
            _ => return Err(usage.into()),
        }
    }
    let view = read_json(&root.join(VIEW))?;
    let files = generate(&view)?;
    if check { compare(&out, &files) } else { write(&out, &files) }
}

/// This crate sits at `rust/xtask`, two below the workspace root.
fn workspace_root() -> PathBuf {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    root.canonicalize().unwrap_or(root)
}

fn read_json(path: &Path) -> Result<Value, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))
}

/// The five files, name and contents, in a fixed order.
fn generate(view: &Value) -> Result<Vec<(&'static str, String)>, String> {
    let streams = streams::read(view)?;
    let events = events::read(view)?;
    let models = models(view, &streams)?;
    let routes = render(streams::render(&streams))?;
    Ok(vec![
        ("events.rs", format!("{HEADER}{}", render(events::render(&events))?)),
        ("mod.rs", format!("{HEADER}{MOD_RS}")),
        ("models.rs", format!("{HEADER}{models}")),
        ("spec_version.rs", format!("{HEADER}{}", spec_version(view)?)),
        ("streams.rs", format!("{HEADER}{routes}")),
    ])
}

/// `GENERATED_FOR_VERSION`: the view's `info.version`, the frozen /v1 version
/// the models describe (ADR 30.9.26a §4).
fn spec_version(view: &Value) -> Result<String, String> {
    let id = view.pointer("/info/version").and_then(Value::as_str).ok_or("the view has no info.version")?;
    Ok(format!(
        "/// The /v1 version this crate's models were generated from.\npub const GENERATED_FOR_VERSION: &str = {id:?};\n"
    ))
}

fn models(view: &Value, streams: &[Stream]) -> Result<String, String> {
    let schemas = view
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .ok_or("the view has no components.schemas")?;
    let skip: BTreeSet<&str> = streams.iter().flat_map(Stream::component_names).collect();
    let mut defs = Vec::new();
    for (name, schema) in schemas.iter().filter(|(name, _)| !skip.contains(name.as_str())) {
        let mut schema = schema.clone();
        strip_string_formats(&mut schema);
        let schema = serde_json::from_value(schema).map_err(|e| format!("schema {name}: {e}"))?;
        defs.push((name.clone(), schema));
    }
    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    let mut space = TypeSpace::new(&settings);
    space.add_ref_types(defs).map_err(|e| format!("typify: {e}"))?;
    render(space.to_stream())
}

fn strip_string_formats(value: &mut Value) {
    match value {
        Value::Object(map) => strip_in_object(map),
        Value::Array(items) => items.iter_mut().for_each(strip_string_formats),
        _ => {}
    }
}

fn strip_in_object(map: &mut Map<String, Value>) {
    if map.get("format").and_then(Value::as_str).is_some_and(|f| STRING_FORMATS.contains(&f)) {
        map.remove("format");
    }
    // A string `pattern` would make typify validate through the `regress`
    // crate, a runtime dependency the library does not take; the server
    // checks it (ADR 30.9.26aa D4's dependency rule). A property *named*
    // `pattern` holds an object, so it stays.
    if map.get("pattern").is_some_and(Value::is_string) {
        map.remove("pattern");
    }
    map.values_mut().for_each(strip_string_formats);
}

fn render(tokens: proc_macro2::TokenStream) -> Result<String, String> {
    let file: syn::File = syn::parse2(tokens).map_err(|e| format!("generated code does not parse: {e}"))?;
    Ok(prettyplease::unparse(&file))
}

fn write(out: &Path, files: &[(&str, String)]) -> Result<(), String> {
    std::fs::create_dir_all(out).map_err(|e| format!("{}: {e}", out.display()))?;
    for (name, contents) in files {
        let path = out.join(name);
        std::fs::write(&path, contents).map_err(|e| format!("{}: {e}", path.display()))?;
    }
    println!("✓ wrote {} files to {}", files.len(), out.display());
    Ok(())
}

fn compare(out: &Path, files: &[(&str, String)]) -> Result<(), String> {
    let stale: Vec<&str> = files
        .iter()
        .filter(|(name, contents)| std::fs::read_to_string(out.join(name)).ok().as_deref() != Some(contents.as_str()))
        .map(|(name, _)| *name)
        .collect();
    if !stale.is_empty() {
        return Err(format!("{} is stale ({}): run make codegen-rust", out.display(), stale.join(", ")));
    }
    println!("✓ {} is current", out.display());
    Ok(())
}
