<?php

// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.

declare(strict_types=1);

namespace Lingara\Internal;

use Lingara\Exception\TransportException;
use Lingara\Exception\TransportKind;
use Lingara\ObjectSerializer;

/**
 * Every operation's route, keyed by operationId: from `paths` for a JSON
 * operation and from `x-lingara-streams` for a stream. A stream's events
 * are in source order; each has its class (null when it is never
 * yielded), its `data` model and its end: 'yield' (yielded, then the
 * stream ends), 'quiet' (a Done payload, never yielded), 'raise' (the
 * error event) or null (the stream goes on).
 *
 * @internal
 */
final class Operations
{
    public const OPERATIONS = [
        'createLessonPlan' => [
            'method' => 'POST',
            'path' => '/v1/lesson-plans',
            'pathParams' => [],
            'needsToken' => true,
            'request' => \Lingara\Model\LessonPlanCreateRequest::class,
            'response' => null,
            'stream' => [
                'union' => \Lingara\Stream\CreateLessonPlanEvent::class,
                'events' => [
                    'started' => ['class' => \Lingara\Stream\CreateLessonPlanEvent\Started::class, 'data' => \Lingara\Model\PlanStarted::class, 'end' => null],
                    'phase' => ['class' => \Lingara\Stream\CreateLessonPlanEvent\Phase::class, 'data' => \Lingara\Model\PlanPhase::class, 'end' => null],
                    'result' => ['class' => \Lingara\Stream\CreateLessonPlanEvent\Result::class, 'data' => \Lingara\Model\PlanResult::class, 'end' => 'yield'],
                    'error' => ['class' => null, 'data' => \Lingara\Model\StreamError::class, 'end' => 'raise'],
                ],
            ],
        ],
        'generateVocabulary' => [
            'method' => 'POST',
            'path' => '/v1/vocab/stream',
            'pathParams' => [],
            'needsToken' => true,
            'request' => \Lingara\Model\VocabRequest::class,
            'response' => null,
            'stream' => [
                'union' => \Lingara\Stream\GenerateVocabularyEvent::class,
                'events' => [
                    'started' => ['class' => \Lingara\Stream\GenerateVocabularyEvent\Started::class, 'data' => \Lingara\Model\VocabStarted::class, 'end' => null],
                    'item' => ['class' => \Lingara\Stream\GenerateVocabularyEvent\Item::class, 'data' => \Lingara\Model\VocabItem::class, 'end' => null],
                    'done' => ['class' => null, 'data' => null, 'end' => 'quiet'],
                    'error' => ['class' => null, 'data' => \Lingara\Model\StreamError::class, 'end' => 'raise'],
                ],
            ],
        ],
        'getApiVersion' => [
            'method' => 'GET',
            'path' => '/v1/versions/{id}',
            'pathParams' => ['id'],
            'needsToken' => false,
            'request' => null,
            'response' => \Lingara\Model\VersionDetail::class,
            'stream' => null,
        ],
        'getLessonPlan' => [
            'method' => 'GET',
            'path' => '/v1/lesson-plans/{id}',
            'pathParams' => ['id'],
            'needsToken' => true,
            'request' => null,
            'response' => \Lingara\Model\LessonPlan::class,
            'stream' => null,
        ],
        'getOpenApiDocument' => [
            'method' => 'GET',
            'path' => '/v1/openapi.json',
            'pathParams' => [],
            'needsToken' => false,
            'request' => null,
            'response' => null,
            'stream' => null,
        ],
        'getUsage' => [
            'method' => 'GET',
            'path' => '/v1/usage',
            'pathParams' => [],
            'needsToken' => true,
            'request' => null,
            'response' => \Lingara\Model\Usage::class,
            'stream' => null,
        ],
        'listApiVersions' => [
            'method' => 'GET',
            'path' => '/v1/versions',
            'pathParams' => [],
            'needsToken' => false,
            'request' => null,
            'response' => \Lingara\Model\VersionList::class,
            'stream' => null,
        ],
        'sendTutorMessage' => [
            'method' => 'POST',
            'path' => '/v1/tutor/message',
            'pathParams' => [],
            'needsToken' => true,
            'request' => \Lingara\Model\TutorTurnRequest::class,
            'response' => null,
            'stream' => [
                'union' => \Lingara\Stream\SendTutorMessageEvent::class,
                'events' => [
                    'delta' => ['class' => \Lingara\Stream\SendTutorMessageEvent\Delta::class, 'data' => \Lingara\Model\TurnDelta::class, 'end' => null],
                    'notice' => ['class' => \Lingara\Stream\SendTutorMessageEvent\Notice::class, 'data' => \Lingara\Model\Notice::class, 'end' => null],
                    'done' => ['class' => null, 'data' => null, 'end' => 'quiet'],
                    'error' => ['class' => null, 'data' => \Lingara\Model\StreamError::class, 'end' => 'raise'],
                ],
            ],
        ],
        'streamLessonPlan' => [
            'method' => 'GET',
            'path' => '/v1/lesson-plans/{id}/stream',
            'pathParams' => ['id'],
            'needsToken' => true,
            'request' => null,
            'response' => null,
            'stream' => [
                'union' => \Lingara\Stream\StreamLessonPlanEvent::class,
                'events' => [
                    'started' => ['class' => \Lingara\Stream\StreamLessonPlanEvent\Started::class, 'data' => \Lingara\Model\PlanStarted::class, 'end' => null],
                    'phase' => ['class' => \Lingara\Stream\StreamLessonPlanEvent\Phase::class, 'data' => \Lingara\Model\PlanPhase::class, 'end' => null],
                    'result' => ['class' => \Lingara\Stream\StreamLessonPlanEvent\Result::class, 'data' => \Lingara\Model\PlanResult::class, 'end' => 'yield'],
                    'pending' => ['class' => \Lingara\Stream\StreamLessonPlanEvent\Pending::class, 'data' => \Lingara\Model\PlanPending::class, 'end' => 'yield'],
                    'error' => ['class' => null, 'data' => \Lingara\Model\StreamError::class, 'end' => 'raise'],
                ],
            ],
        ],
    ];

    /**
     * The event object for a known, yielded event name, or null for an
     * unknown one. $data is the frame's `data` decoded as objects.
     *
     * @throws TransportException MalformedEvent when a known event's data
     *                            is not a JSON object or does not decode
     */
    public static function decode(string $operationId, string $name, mixed $data): ?object
    {
        $event = self::OPERATIONS[$operationId]['stream']['events'][$name] ?? null;
        if ($event === null || $event['class'] === null) {
            return null;
        }
        if (!$data instanceof \stdClass) {
            throw new TransportException(TransportKind::MalformedEvent, "{$name}: data is not a JSON object");
        }
        try {
            return new $event['class'](ObjectSerializer::deserialize($data, $event['data']));
        } catch (\Throwable) {
            throw new TransportException(TransportKind::MalformedEvent, "{$name}: data does not decode");
        }
    }
}
