// Writes src/generated/events.ts from the generator view's
// `x-lingara-events` (ADR 30.9.26aa D3): the `Event` union, one arm per
// outbound type plus `UnknownEvent`; `InboundEvent`, one constructor per
// inbound type; and `parseEvent`.
//
// openapi-typescript's models are types only, so a known type's `data` is
// checked against a small structural shape emitted here from its schema
// (required keys, primitive types, enums, array items, `null`): never a
// hand-written check per type, and never more than D3's "does not decode".
//
// Usage: node scripts/codegenEvents.mjs <view.json> <out.ts>
// Node only, no dependencies.

import { readFileSync, writeFileSync } from "node:fs";

const [viewPath, outPath] = process.argv.slice(2);
if (!viewPath || !outPath) {
  console.error("usage: codegenEvents.mjs <view.json> <out.ts>");
  process.exit(2);
}

const view = JSON.parse(readFileSync(viewPath, "utf8"));
const catalogue = view["x-lingara-events"];
if (!Array.isArray(catalogue) || catalogue.length === 0) {
  console.error(`${viewPath}: no x-lingara-events`);
  process.exit(1);
}

const SCHEMA_PREFIX = "#/components/schemas/";
const schemas = view.components.schemas;
// The names this file generates, which no model may also carry.
const GENERATED = ["Event", "UnknownEvent", "InboundEvent", "EventOf"];

function fail(message) {
  console.error(`${viewPath}: ${message}`);
  process.exit(1);
}

function component(ref) {
  if (typeof ref !== "string" || !ref.startsWith(SCHEMA_PREFIX)) fail(`unexpected data ref: ${JSON.stringify(ref)}`);
  const name = ref.slice(SCHEMA_PREFIX.length);
  if (!Object.hasOwn(schemas, name)) fail(`data ref names no component: ${ref}`);
  return name;
}

const outbound = catalogue.filter((e) => e.direction === "out");
const inbound = catalogue.filter((e) => e.direction === "in");
if (outbound.length + inbound.length !== catalogue.length) fail("an x-lingara-events entry has no direction");

// D3: a generated model named after an arm would ship two types for one name.
for (const name of [...outbound.map((e) => e.arm), ...GENERATED]) {
  if (typeof name !== "string" || name === "") fail("an outbound entry has no arm");
  if (Object.hasOwn(schemas, name)) fail(`the model ${name} is named after an Event arm; rename or exclude it`);
}

// The structural shape of a schema: $refs inlined, documentation and
// formats dropped. `type` is always a list; `null` is a type like any other.
function shape(schema, depth = 0) {
  if (depth > 16) fail("a data schema nests too deeply to shape");
  if (schema.$ref) return shape(schemas[component(schema.$ref)], depth + 1);
  const out = {};
  if (schema.type !== undefined) out.type = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (Array.isArray(schema.enum)) out.enum = schema.enum;
  return { ...out, ...nested(schema, depth + 1) };
}

// The parts of a shape that are shapes themselves.
function nested(schema, depth) {
  const out = {};
  const any = schema.anyOf ?? schema.oneOf;
  if (Array.isArray(any)) out.anyOf = any.map((s) => shape(s, depth));
  if (schema.items) out.items = shape(schema.items, depth);
  if (schema.properties) {
    out.properties = Object.fromEntries(Object.entries(schema.properties).map(([k, s]) => [k, shape(s, depth)]));
  }
  if (Array.isArray(schema.required) && schema.required.length > 0) out.required = schema.required;
  return out;
}

const camel = (name) => name[0].toLowerCase() + name.slice(1);

function armType(e) {
  return [
    `/** \`${e.type}\`. */`,
    `export type ${e.arm} = EventOf<${JSON.stringify(e.type)}, Schemas[${JSON.stringify(component(e.data))}]>;`,
  ].join("\n");
}

const inboundNames = inbound.map((e) => component(e.data));
if (new Set(inboundNames).size !== inboundNames.length) fail("two inbound entries name one data component");

const inboundUnion = inbound
  .map((e) => `  | { readonly type: ${JSON.stringify(e.type)}; readonly data: Schemas[${JSON.stringify(component(e.data))}] }`)
  .join("\n");

const inboundConstructors = inbound
  .map((e) => {
    const name = component(e.data);
    return `  /** \`${e.type}\`. */\n  ${camel(name)}: (data: Schemas[${JSON.stringify(name)}]): InboundEvent => ({ type: ${JSON.stringify(e.type)}, data }),`;
  })
  .join("\n");

const shapes = outbound
  .map((e) => `  ${JSON.stringify(e.type)}: ${JSON.stringify(shape(schemas[component(e.data)]))},`)
  .join("\n");

const out = `// Generated by scripts/codegenEvents.mjs from the generator view's
// x-lingara-events (ADR 30.9.26aa D3). Do not edit: run \`make codegen-typescript\`.

import { TransportError } from "../errors.js";
import type { components } from "./schema.js";

type Schemas = components["schemas"];

/** The envelope every event carries, with its type and its typed \`data\`. */
export interface EventOf<T extends string, D> {
  readonly id: string;
  readonly type: T;
  readonly createdAt: string;
  readonly apiVersion: string;
  readonly subject: string;
  readonly data: D;
}

${outbound.map(armType).join("\n\n")}

const UNKNOWN = Symbol.for("lingara.event.UnknownEvent");

/**
 * An event type this library does not know: the catalogue is additive, so a
 * newer type than the library is this, never an error. Acknowledge it (and
 * log it), or the sender keeps retrying it.
 */
export class UnknownEvent implements EventOf<string, unknown> {
  static [Symbol.hasInstance](value: unknown): value is UnknownEvent {
    return typeof value === "object" && value !== null && (value as Record<symbol, unknown>)[UNKNOWN] === true;
  }

  // Nominal, so a known arm is never mistaken for this one by the compiler.
  readonly #unknown = true;
  readonly id: string;
  readonly type: string;
  readonly createdAt: string;
  readonly apiVersion: string;
  readonly subject: string;
  /** The raw JSON value. */
  readonly data: unknown;

  constructor(fields: EventOf<string, unknown>) {
    Object.defineProperty(this, UNKNOWN, { value: this.#unknown, enumerable: false });
    this.id = fields.id;
    this.type = fields.type;
    this.createdAt = fields.createdAt;
    this.apiVersion = fields.apiVersion;
    this.subject = fields.subject;
    this.data = fields.data;
  }
}

/** Every outbound event, discriminated on \`type\`; \`instanceof UnknownEvent\` first. */
export type Event =
${outbound.map((e) => `  | ${e.arm}`).join("\n")}
  | UnknownEvent;

/** An event your game sends with \`sendEvent\`, serialised as \`{type, data}\`. */
export type InboundEvent =
${inboundUnion};

/** One constructor per inbound type, named after its \`data\` model. */
export const InboundEvent = {
${inboundConstructors}
} as const;

interface Shape {
  type?: string[];
  enum?: unknown[];
  anyOf?: Shape[];
  items?: Shape;
  properties?: Record<string, Shape>;
  required?: string[];
}

const SHAPES: Record<string, Shape> = {
${shapes}
};

function isType(type: string, value: unknown): boolean {
  if (type === "null") return value === null;
  if (type === "array") return Array.isArray(value);
  if (type === "object") return typeof value === "object" && value !== null && !Array.isArray(value);
  if (type === "integer") return Number.isInteger(value);
  return typeof value === type;
}

function conforms(s: Shape, value: unknown): boolean {
  if (s.anyOf && !s.anyOf.some((a) => conforms(a, value))) return false;
  if (s.enum && !s.enum.includes(value)) return false;
  if (s.type && !s.type.some((t) => isType(t, value))) return false;
  if (Array.isArray(value)) return !s.items || value.every((v) => conforms(s.items!, v));
  if (typeof value !== "object" || value === null) return true;
  const o = value as Record<string, unknown>;
  if (!(s.required ?? []).every((k) => Object.hasOwn(o, k))) return false;
  // An optional key sent as null is read as absent.
  const present = Object.entries(s.properties ?? {}).filter(([k]) => Object.hasOwn(o, k) && (o[k] !== null || s.required?.includes(k)));
  return present.every(([k, p]) => conforms(p, o[k]));
}

const ENVELOPE = ["id", "type", "created_at", "api_version", "subject"] as const;

function envelope(value: unknown): EventOf<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TransportError("malformed_event");
  const o = value as Record<string, unknown>;
  if (!ENVELOPE.every((k) => typeof o[k] === "string") || !Object.hasOwn(o, "data")) throw new TransportError("malformed_event");
  const [id, type, createdAt, apiVersion, subject] = ENVELOPE.map((k) => o[k] as string) as [string, string, string, string, string];
  return { id, type, createdAt, apiVersion, subject, data: o["data"] };
}

/**
 * One event from its JSON (text, or an already-decoded value). A known type
 * is its arm; an unknown type is \`UnknownEvent\`. Throws
 * \`TransportError{kind: "malformed_event"}\` for anything that is not an
 * envelope, or a known type whose \`data\` does not decode.
 */
export function parseEvent(json: unknown): Event {
  let value = json;
  if (typeof json === "string") {
    try {
      value = JSON.parse(json);
    } catch {
      throw new TransportError("malformed_event");
    }
  }
  const event = envelope(value);
  const s = Object.hasOwn(SHAPES, event.type) ? SHAPES[event.type] : undefined;
  if (s === undefined) return new UnknownEvent(event);
  if (!conforms(s, event.data)) throw new TransportError("malformed_event");
  return event as Event;
}
`;

writeFileSync(outPath, out);
