// Writes src/generated/streams.ts from the generator view's
// `x-lingara-streams`.
//
// openapi-typescript does not read that extension, and the view has stripped
// the four stream operations from `paths`, so their routes, request bodies
// and event names would otherwise be hand-copied. This script keeps them
// generated: a stream the spec gains or renames is a diff here.
//
// Usage: node scripts/codegenStreams.mjs <view.json> <out.ts>
// Node only, no dependencies.

import { readFileSync, writeFileSync } from "node:fs";

const [viewPath, outPath] = process.argv.slice(2);
if (!viewPath || !outPath) {
  console.error("usage: codegenStreams.mjs <view.json> <out.ts>");
  process.exit(2);
}

const view = JSON.parse(readFileSync(viewPath, "utf8"));
const streams = view["x-lingara-streams"];
if (!Array.isArray(streams) || streams.length === 0) {
  console.error(`${viewPath}: no x-lingara-streams`);
  process.exit(1);
}

const SCHEMA_PREFIX = "#/components/schemas/";

const DONE_REF = `${SCHEMA_PREFIX}Done`;

function schemaName(ref, what = "requestBody") {
  if (ref === null || ref === undefined) return null;
  if (typeof ref !== "string" || !ref.startsWith(SCHEMA_PREFIX)) {
    throw new Error(`unexpected ${what} ref: ${JSON.stringify(ref)}`);
  }
  return ref.slice(SCHEMA_PREFIX.length);
}

// CONTRACT.md K5's rule over the view (ADR 29.9.26ai D2): the entry's
// `error` event raises, an ending event whose payload is `Done` ends
// unyielded, and any other ending event is yielded and then ends.
function outcome(s, event) {
  if (event === s.error) return "raise";
  const schemas = view.components.schemas;
  const branch = schemas[schemaName(schemas[s.union].discriminator.mapping[event], "branch")];
  return branch.properties.data.$ref === DONE_REF ? "end" : "yield";
}

function ends(s) {
  if (!Array.isArray(s.endsOn) || s.endsOn.length === 0) {
    throw new Error(`${s.operationId}: no endsOn; the view predates ADR 29.9.26ai`);
  }
  return s.endsOn.map((e) => `${e}: ${JSON.stringify(outcome(s, e))}`).join(", ");
}

function entry(s) {
  const body = schemaName(s.requestBody);
  const lines = [
    `  ${s.operationId}: {`,
    `    method: ${JSON.stringify(s.method.toUpperCase())},`,
    `    path: ${JSON.stringify(s.path)},`,
    `    requestBody: ${JSON.stringify(body)},`,
    `    union: ${JSON.stringify(s.union)},`,
    `    events: [${s.events.map((e) => JSON.stringify(e)).join(", ")}],`,
    `    ends: { ${ends(s)} },`,
    `  },`,
  ];
  return lines.join("\n");
}

const out = `// Generated by scripts/codegenStreams.mjs from the generator view's
// x-lingara-streams. Do not edit: run \`make codegen-typescript\`.

export const STREAMS = {
${streams.map(entry).join("\n")}
} as const;

export type StreamOperation = keyof typeof STREAMS;

/** What an ending event does to iteration (CONTRACT.md K5's rule). */
export type StreamOutcome = "yield" | "end" | "raise";
`;

writeFileSync(outPath, out);
