# Generated by ruby/codegen/generate.rb from the generator view. DO NOT EDIT.

module Lingara
  # Every operation's route, keyed by operationId: from `paths` for a JSON
  # operation and from `x-lingara-streams` for a stream. A stream's `ends`
  # is its terminal table: :yield (yielded, then the stream ends), :quiet
  # (a Done payload, never yielded) and :raise (the error event).
  OPERATIONS = {
    "createLessonPlan" => {
      method: "POST",
      path: "/v1/lesson-plans",
      path_params: [].freeze,
      needs_token: true,
      request_body: "LessonPlanCreateRequest",
      response: nil,
      stream: {union: "CreateLessonPlanEvent", events: {"started" => "CreateLessonPlanEventStarted", "phase" => "CreateLessonPlanEventPhase", "result" => "CreateLessonPlanEventResult", "error" => "CreateLessonPlanEventError"}.freeze, ends: {"result" => :yield, "error" => :raise}.freeze}.freeze
    }.freeze,
    "generateVocabulary" => {
      method: "POST",
      path: "/v1/vocab/stream",
      path_params: [].freeze,
      needs_token: true,
      request_body: "VocabRequest",
      response: nil,
      stream: {union: "GenerateVocabularyEvent", events: {"started" => "GenerateVocabularyEventStarted", "item" => "GenerateVocabularyEventItem", "done" => "GenerateVocabularyEventDone", "error" => "GenerateVocabularyEventError"}.freeze, ends: {"done" => :quiet, "error" => :raise}.freeze}.freeze
    }.freeze,
    "getApiVersion" => {
      method: "GET",
      path: "/v1/versions/{id}",
      path_params: ["id"].freeze,
      needs_token: false,
      request_body: nil,
      response: "VersionDetail",
      stream: nil
    }.freeze,
    "getLessonPlan" => {
      method: "GET",
      path: "/v1/lesson-plans/{id}",
      path_params: ["id"].freeze,
      needs_token: true,
      request_body: nil,
      response: "LessonPlan",
      stream: nil
    }.freeze,
    "getOpenApiDocument" => {
      method: "GET",
      path: "/v1/openapi.json",
      path_params: [].freeze,
      needs_token: false,
      request_body: nil,
      response: nil,
      stream: nil
    }.freeze,
    "getUsage" => {
      method: "GET",
      path: "/v1/usage",
      path_params: [].freeze,
      needs_token: true,
      request_body: nil,
      response: "Usage",
      stream: nil
    }.freeze,
    "listApiVersions" => {
      method: "GET",
      path: "/v1/versions",
      path_params: [].freeze,
      needs_token: false,
      request_body: nil,
      response: "VersionList",
      stream: nil
    }.freeze,
    "sendTutorMessage" => {
      method: "POST",
      path: "/v1/tutor/message",
      path_params: [].freeze,
      needs_token: true,
      request_body: "TutorTurnRequest",
      response: nil,
      stream: {union: "SendTutorMessageEvent", events: {"delta" => "SendTutorMessageEventDelta", "notice" => "SendTutorMessageEventNotice", "done" => "SendTutorMessageEventDone", "error" => "SendTutorMessageEventError"}.freeze, ends: {"done" => :quiet, "error" => :raise}.freeze}.freeze
    }.freeze,
    "streamLessonPlan" => {
      method: "GET",
      path: "/v1/lesson-plans/{id}/stream",
      path_params: ["id"].freeze,
      needs_token: true,
      request_body: nil,
      response: nil,
      stream: {union: "StreamLessonPlanEvent", events: {"started" => "StreamLessonPlanEventStarted", "phase" => "StreamLessonPlanEventPhase", "result" => "StreamLessonPlanEventResult", "pending" => "StreamLessonPlanEventPending", "error" => "StreamLessonPlanEventError"}.freeze, ends: {"result" => :yield, "pending" => :yield, "error" => :raise}.freeze}.freeze
    }.freeze
  }.freeze
end
