# Generated by ruby/codegen/generate.rb from the generator view. DO NOT EDIT.

module Lingara
  # One event of createLessonPlan's stream: `case event in CreateLessonPlanEvent` matches
  # any of its branches. The error branch, and a Done-bodied one, are never
  # yielded.
  module CreateLessonPlanEvent
    BRANCHES = {
      "started" => CreateLessonPlanEventStarted,
      "phase" => CreateLessonPlanEventPhase,
      "result" => CreateLessonPlanEventResult,
      "error" => CreateLessonPlanEventError
    }.freeze

    def self.===(other)
      BRANCHES.value?(other.class)
    end

    # The branch for a known event name, decoded from its `data` JSON text,
    # or nil for an unknown name. A known event whose data is not a JSON
    # object, or that its branch refuses, raises TransportError
    # :malformed_event.
    def self.decode(name, data)
      branch = BRANCHES[name]
      branch && Lingara::Decoding.event(branch, name, data)
    end
  end

  # One event of generateVocabulary's stream: `case event in GenerateVocabularyEvent` matches
  # any of its branches. The error branch, and a Done-bodied one, are never
  # yielded.
  module GenerateVocabularyEvent
    BRANCHES = {
      "started" => GenerateVocabularyEventStarted,
      "item" => GenerateVocabularyEventItem,
      "done" => GenerateVocabularyEventDone,
      "error" => GenerateVocabularyEventError
    }.freeze

    def self.===(other)
      BRANCHES.value?(other.class)
    end

    # The branch for a known event name, decoded from its `data` JSON text,
    # or nil for an unknown name. A known event whose data is not a JSON
    # object, or that its branch refuses, raises TransportError
    # :malformed_event.
    def self.decode(name, data)
      branch = BRANCHES[name]
      branch && Lingara::Decoding.event(branch, name, data)
    end
  end

  # One event of sendTutorMessage's stream: `case event in SendTutorMessageEvent` matches
  # any of its branches. The error branch, and a Done-bodied one, are never
  # yielded.
  module SendTutorMessageEvent
    BRANCHES = {
      "delta" => SendTutorMessageEventDelta,
      "notice" => SendTutorMessageEventNotice,
      "done" => SendTutorMessageEventDone,
      "error" => SendTutorMessageEventError
    }.freeze

    def self.===(other)
      BRANCHES.value?(other.class)
    end

    # The branch for a known event name, decoded from its `data` JSON text,
    # or nil for an unknown name. A known event whose data is not a JSON
    # object, or that its branch refuses, raises TransportError
    # :malformed_event.
    def self.decode(name, data)
      branch = BRANCHES[name]
      branch && Lingara::Decoding.event(branch, name, data)
    end
  end

  # One event of streamLessonPlan's stream: `case event in StreamLessonPlanEvent` matches
  # any of its branches. The error branch, and a Done-bodied one, are never
  # yielded.
  module StreamLessonPlanEvent
    BRANCHES = {
      "started" => StreamLessonPlanEventStarted,
      "phase" => StreamLessonPlanEventPhase,
      "result" => StreamLessonPlanEventResult,
      "pending" => StreamLessonPlanEventPending,
      "error" => StreamLessonPlanEventError
    }.freeze

    def self.===(other)
      BRANCHES.value?(other.class)
    end

    # The branch for a known event name, decoded from its `data` JSON text,
    # or nil for an unknown name. A known event whose data is not a JSON
    # object, or that its branch refuses, raises TransportError
    # :malformed_event.
    def self.decode(name, data)
      branch = BRANCHES[name]
      branch && Lingara::Decoding.event(branch, name, data)
    end
  end
end
