// Command codegen writes the Go library's streams_gen.go, routes_gen.go and
// version_gen.go (ADR 29.9.26q D2). oapi-codegen writes the models but reads
// neither x-lingara-streams nor, in models-only mode, any route, and its
// oneOf output would import its runtime package. So this reads the same 3.0
// generator view and writes, through go/format:
//
//   - streams_gen.go: each stream's union as a sealed interface, the marker
//     method on each of oapi-codegen's branch structs, and one decoder;
//   - routes_gen.go: every operation's method and path, whether it needs a
//     token, and for a stream its body, event names and terminal table;
//   - version_gen.go: the library's Version, from VERSION, and the /v1
//     version the models were generated from, from the view's info.version.
//
// It has no dependency, like the library it writes.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// header opens every file this writes. The phrase is Go's convention for a
// generated file, which linters and gofmt checks recognise.
const header = "// Code generated by go/codegen from the generator view (spec/generator/openapi.3.0.json). DO NOT EDIT.\n\npackage lingara\n"

type view struct {
	Info struct {
		Version string `json:"version"`
	} `json:"info"`
	Paths      map[string]map[string]json.RawMessage `json:"paths"`
	Streams    []streamEntry                         `json:"x-lingara-streams"`
	Components struct {
		Schemas map[string]schema `json:"schemas"`
	} `json:"components"`
}

type streamEntry struct {
	OperationID string   `json:"operationId"`
	Method      string   `json:"method"`
	Path        string   `json:"path"`
	RequestBody *string  `json:"requestBody"`
	Scopes      []string `json:"scopes"`
	Union       string   `json:"union"`
	Events      []string `json:"events"`
	EndsOn      []string `json:"endsOn"`
	Error       string   `json:"error"`
}

type schema struct {
	Properties map[string]struct {
		Ref string `json:"$ref"`
	} `json:"properties"`
	Discriminator *struct {
		Mapping map[string]string `json:"mapping"`
	} `json:"discriminator"`
}

type operation struct {
	OperationID string             `json:"operationId"`
	Security    *[]json.RawMessage `json:"security"`
}

// route is one operation as routes_gen.go writes it.
type route struct {
	operationID, method, path string
	needsToken                bool
	stream                    *stream
}

// stream is a stream operation's union, body and events.
type stream struct {
	union, requestBody string
	events             []event
	ends               []ending
}

type event struct{ name, branch string }

// ending is one endsOn event and what it does (CONTRACT.md K5, Ending).
type ending struct{ name, outcome string }

func main() {
	viewPath := flag.String("view", "", "the 3.0 generator view")
	versionPath := flag.String("version", "", "the repository's VERSION file")
	out := flag.String("out", "", "the directory to write the three files into")
	flag.Parse()
	if *viewPath == "" || *versionPath == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: codegen -view <openapi.3.0.json> -version <VERSION> -out <dir>")
		os.Exit(2)
	}
	if err := run(*viewPath, *versionPath, *out); err != nil {
		fmt.Fprintln(os.Stderr, "✗ codegen:", err)
		os.Exit(1)
	}
}

func run(viewPath, versionPath, out string) error {
	files, err := generate(viewPath, versionPath)
	if err != nil {
		return err
	}
	for _, name := range []string{"streams_gen.go", "routes_gen.go", "version_gen.go"} {
		if err := os.WriteFile(filepath.Join(out, name), files[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}

// generate returns the three files' formatted bytes, keyed by file name.
func generate(viewPath, versionPath string) (map[string][]byte, error) {
	raw, err := os.ReadFile(viewPath)
	if err != nil {
		return nil, err
	}
	var v view
	if err := json.Unmarshal(raw, &v); err != nil {
		return nil, fmt.Errorf("%s: %w", viewPath, err)
	}
	version, err := os.ReadFile(versionPath)
	if err != nil {
		return nil, err
	}
	if strings.TrimSpace(string(version)) == "" || v.Info.Version == "" {
		return nil, errors.New("VERSION and the view's info.version must both be set")
	}
	routes, err := collect(&v)
	if err != nil {
		return nil, err
	}
	sources := map[string]string{
		"streams_gen.go": streamsSource(routes),
		"routes_gen.go":  routesSource(routes),
		"version_gen.go": versionSource(strings.TrimSpace(string(version)), v.Info.Version),
	}
	files := make(map[string][]byte, len(sources))
	for name, src := range sources {
		formatted, err := format.Source([]byte(src))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		files[name] = formatted
	}
	return files, nil
}

// collect returns every operation, sorted by operationId: the JSON ones from
// paths and the streams from x-lingara-streams, which paths no longer has.
func collect(v *view) ([]route, error) {
	routes, err := jsonRoutes(v.Paths)
	if err != nil {
		return nil, err
	}
	for _, entry := range v.Streams {
		r, err := streamRoute(entry, v.Components.Schemas)
		if err != nil {
			return nil, err
		}
		routes = append(routes, r)
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].operationID < routes[j].operationID })
	return routes, nil
}

var methods = []string{"get", "put", "post", "delete", "patch"}

func jsonRoutes(paths map[string]map[string]json.RawMessage) ([]route, error) {
	var routes []route
	for path, item := range paths {
		for _, method := range methods {
			raw, ok := item[method]
			if !ok {
				continue
			}
			var op operation
			if err := json.Unmarshal(raw, &op); err != nil {
				return nil, fmt.Errorf("%s %s: %w", method, path, err)
			}
			if op.OperationID == "" {
				return nil, fmt.Errorf("%s %s: no operationId", method, path)
			}
			// The view has no global security, so an operation with no
			// `security` of its own, or an empty one, needs no token.
			needs := op.Security != nil && len(*op.Security) > 0
			routes = append(routes, route{op.OperationID, strings.ToUpper(method), path, needs, nil})
		}
	}
	return routes, nil
}

func streamRoute(e streamEntry, schemas map[string]schema) (route, error) {
	union, ok := schemas[e.Union]
	if !ok || union.Discriminator == nil {
		return route{}, fmt.Errorf("%s: no discriminated union %q", e.OperationID, e.Union)
	}
	s := &stream{union: e.Union}
	if e.RequestBody != nil {
		s.requestBody = refName(*e.RequestBody)
	}
	for _, name := range e.Events {
		branch := refName(union.Discriminator.Mapping[name])
		if branch == "" {
			return route{}, fmt.Errorf("%s: event %q has no branch in %s", e.OperationID, name, e.Union)
		}
		s.events = append(s.events, event{name, branch})
	}
	ends, err := endings(e, s.events, schemas)
	if err != nil {
		return route{}, err
	}
	s.ends = ends
	return route{e.OperationID, strings.ToUpper(e.Method), e.Path, len(e.Scopes) > 0, s}, nil
}

// endings applies CONTRACT.md K5's rule to endsOn: the entry's error event
// raises, an ending event whose data is `Done` ends quietly, and any other
// is yielded and then ends.
func endings(e streamEntry, events []event, schemas map[string]schema) ([]ending, error) {
	if len(e.EndsOn) == 0 {
		return nil, fmt.Errorf("%s: no endsOn; the view predates ADR 29.9.26ai", e.OperationID)
	}
	var ends []ending
	for _, name := range e.EndsOn {
		branch := ""
		for _, ev := range events {
			if ev.name == name {
				branch = ev.branch
			}
		}
		if branch == "" {
			return nil, fmt.Errorf("%s: endsOn names unknown event %q", e.OperationID, name)
		}
		outcome := "endYield"
		if name == e.Error {
			outcome = "endRaise"
		} else if refName(schemas[branch].Properties["data"].Ref) == "Done" {
			outcome = "endQuiet"
		}
		ends = append(ends, ending{name, outcome})
	}
	return ends, nil
}

// refName is the last segment of a `#/components/schemas/<Name>` reference.
func refName(ref string) string {
	return ref[strings.LastIndex(ref, "/")+1:]
}

func streamsSource(routes []route) string {
	var b strings.Builder
	b.WriteString(header + "\nimport \"encoding/json\"\n")
	for _, r := range routes {
		if r.stream == nil {
			continue
		}
		s := r.stream
		fmt.Fprintf(&b, "\n// %s is one event of %s's stream: type-switch on its\n", s.union, r.operationID)
		b.WriteString("// concrete branch. The error branch, and a Done-bodied one, are never yielded.\n")
		fmt.Fprintf(&b, "type %s interface{ is%s() }\n\n", s.union, s.union)
		for _, ev := range s.events {
			fmt.Fprintf(&b, "func (%s) is%s() {}\n", ev.branch, s.union)
		}
		writeDecoder(&b, s)
	}
	return b.String()
}

// writeDecoder writes decode<Union>: a switch on the event name that
// unmarshals into the concrete branch, so a known event whose data has the
// wrong shape fails here, before it can be yielded. An unknown name is false.
func writeDecoder(b *strings.Builder, s *stream) {
	fmt.Fprintf(b, "\nfunc decode%s(name string, frame []byte) (%s, bool, error) {\n\tswitch name {\n", s.union, s.union)
	for _, ev := range s.events {
		// The error is taken first: Go leaves unspecified whether `e` in a
		// return list is read before or after a call beside it.
		fmt.Fprintf(b, "\tcase %q:\n\t\tvar e %s\n\t\terr := json.Unmarshal(frame, &e)\n\t\treturn e, true, err\n", ev.name, ev.branch)
	}
	b.WriteString("\t}\n\treturn nil, false, nil\n}\n")
}

func routesSource(routes []route) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n// routes is every operation's method and path, keyed by operationId: from\n")
	b.WriteString("// paths for a JSON operation and from x-lingara-streams for a stream.\n")
	b.WriteString("var routes = map[string]route{\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "%q: {method: %q, path: %q, needsToken: %t", r.operationID, r.method, r.path, r.needsToken)
		if s := r.stream; s != nil {
			names := make([]string, len(s.events))
			for i, ev := range s.events {
				names[i] = fmt.Sprintf("%q", ev.name)
			}
			ends := make([]string, len(s.ends))
			for i, end := range s.ends {
				ends[i] = fmt.Sprintf("%q: %s", end.name, end.outcome)
			}
			fmt.Fprintf(&b, ",\nstream: &streamRoute{requestBody: %q, events: []string{%s}, ends: map[string]ending{%s}}",
				s.requestBody, strings.Join(names, ", "), strings.Join(ends, ", "))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func versionSource(version, generatedFor string) string {
	return header + fmt.Sprintf(`
// Version is this library's released version, sent in every User-Agent (K6).
const Version = %q

// GeneratedForVersion is the /v1 version this library's models were
// generated from. A response served under another version logs one warning
// per version id (ADR 30.9.26a).
const GeneratedForVersion = %q
`, version, generatedFor)
}
