// Package lingara provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package lingara

import (
	"time"
)

const (
	Oauth2Scopes = "oauth2.Scopes"
)

// Defines values for CreateLessonPlanEventErrorEvent.
const (
	CreateLessonPlanEventErrorEventError CreateLessonPlanEventErrorEvent = "error"
)

// Valid indicates whether the value is a known member of the CreateLessonPlanEventErrorEvent enum.
func (e CreateLessonPlanEventErrorEvent) Valid() bool {
	switch e {
	case CreateLessonPlanEventErrorEventError:
		return true
	default:
		return false
	}
}

// Defines values for CreateLessonPlanEventPhaseEvent.
const (
	CreateLessonPlanEventPhaseEventPhase CreateLessonPlanEventPhaseEvent = "phase"
)

// Valid indicates whether the value is a known member of the CreateLessonPlanEventPhaseEvent enum.
func (e CreateLessonPlanEventPhaseEvent) Valid() bool {
	switch e {
	case CreateLessonPlanEventPhaseEventPhase:
		return true
	default:
		return false
	}
}

// Defines values for CreateLessonPlanEventResultEvent.
const (
	CreateLessonPlanEventResultEventResult CreateLessonPlanEventResultEvent = "result"
)

// Valid indicates whether the value is a known member of the CreateLessonPlanEventResultEvent enum.
func (e CreateLessonPlanEventResultEvent) Valid() bool {
	switch e {
	case CreateLessonPlanEventResultEventResult:
		return true
	default:
		return false
	}
}

// Defines values for CreateLessonPlanEventStartedEvent.
const (
	CreateLessonPlanEventStartedEventStarted CreateLessonPlanEventStartedEvent = "started"
)

// Valid indicates whether the value is a known member of the CreateLessonPlanEventStartedEvent enum.
func (e CreateLessonPlanEventStartedEvent) Valid() bool {
	switch e {
	case CreateLessonPlanEventStartedEventStarted:
		return true
	default:
		return false
	}
}

// Defines values for GenerateVocabularyEventDoneEvent.
const (
	GenerateVocabularyEventDoneEventDone GenerateVocabularyEventDoneEvent = "done"
)

// Valid indicates whether the value is a known member of the GenerateVocabularyEventDoneEvent enum.
func (e GenerateVocabularyEventDoneEvent) Valid() bool {
	switch e {
	case GenerateVocabularyEventDoneEventDone:
		return true
	default:
		return false
	}
}

// Defines values for GenerateVocabularyEventErrorEvent.
const (
	GenerateVocabularyEventErrorEventError GenerateVocabularyEventErrorEvent = "error"
)

// Valid indicates whether the value is a known member of the GenerateVocabularyEventErrorEvent enum.
func (e GenerateVocabularyEventErrorEvent) Valid() bool {
	switch e {
	case GenerateVocabularyEventErrorEventError:
		return true
	default:
		return false
	}
}

// Defines values for GenerateVocabularyEventItemEvent.
const (
	GenerateVocabularyEventItemEventItem GenerateVocabularyEventItemEvent = "item"
)

// Valid indicates whether the value is a known member of the GenerateVocabularyEventItemEvent enum.
func (e GenerateVocabularyEventItemEvent) Valid() bool {
	switch e {
	case GenerateVocabularyEventItemEventItem:
		return true
	default:
		return false
	}
}

// Defines values for GenerateVocabularyEventStartedEvent.
const (
	GenerateVocabularyEventStartedEventStarted GenerateVocabularyEventStartedEvent = "started"
)

// Valid indicates whether the value is a known member of the GenerateVocabularyEventStartedEvent enum.
func (e GenerateVocabularyEventStartedEvent) Valid() bool {
	switch e {
	case GenerateVocabularyEventStartedEventStarted:
		return true
	default:
		return false
	}
}

// Defines values for PlanStatus.
const (
	PlanStatusComplete   PlanStatus = "complete"
	PlanStatusGenerating PlanStatus = "generating"
	PlanStatusPartial    PlanStatus = "partial"
)

// Valid indicates whether the value is a known member of the PlanStatus enum.
func (e PlanStatus) Valid() bool {
	switch e {
	case PlanStatusComplete:
		return true
	case PlanStatusGenerating:
		return true
	case PlanStatusPartial:
		return true
	default:
		return false
	}
}

// Defines values for SendTutorMessageEventDeltaEvent.
const (
	SendTutorMessageEventDeltaEventDelta SendTutorMessageEventDeltaEvent = "delta"
)

// Valid indicates whether the value is a known member of the SendTutorMessageEventDeltaEvent enum.
func (e SendTutorMessageEventDeltaEvent) Valid() bool {
	switch e {
	case SendTutorMessageEventDeltaEventDelta:
		return true
	default:
		return false
	}
}

// Defines values for SendTutorMessageEventDoneEvent.
const (
	SendTutorMessageEventDoneEventDone SendTutorMessageEventDoneEvent = "done"
)

// Valid indicates whether the value is a known member of the SendTutorMessageEventDoneEvent enum.
func (e SendTutorMessageEventDoneEvent) Valid() bool {
	switch e {
	case SendTutorMessageEventDoneEventDone:
		return true
	default:
		return false
	}
}

// Defines values for SendTutorMessageEventErrorEvent.
const (
	SendTutorMessageEventErrorEventError SendTutorMessageEventErrorEvent = "error"
)

// Valid indicates whether the value is a known member of the SendTutorMessageEventErrorEvent enum.
func (e SendTutorMessageEventErrorEvent) Valid() bool {
	switch e {
	case SendTutorMessageEventErrorEventError:
		return true
	default:
		return false
	}
}

// Defines values for SendTutorMessageEventNoticeEvent.
const (
	SendTutorMessageEventNoticeEventNotice SendTutorMessageEventNoticeEvent = "notice"
)

// Valid indicates whether the value is a known member of the SendTutorMessageEventNoticeEvent enum.
func (e SendTutorMessageEventNoticeEvent) Valid() bool {
	switch e {
	case SendTutorMessageEventNoticeEventNotice:
		return true
	default:
		return false
	}
}

// Defines values for StreamLessonPlanEventErrorEvent.
const (
	StreamLessonPlanEventErrorEventError StreamLessonPlanEventErrorEvent = "error"
)

// Valid indicates whether the value is a known member of the StreamLessonPlanEventErrorEvent enum.
func (e StreamLessonPlanEventErrorEvent) Valid() bool {
	switch e {
	case StreamLessonPlanEventErrorEventError:
		return true
	default:
		return false
	}
}

// Defines values for StreamLessonPlanEventPendingEvent.
const (
	StreamLessonPlanEventPendingEventPending StreamLessonPlanEventPendingEvent = "pending"
)

// Valid indicates whether the value is a known member of the StreamLessonPlanEventPendingEvent enum.
func (e StreamLessonPlanEventPendingEvent) Valid() bool {
	switch e {
	case StreamLessonPlanEventPendingEventPending:
		return true
	default:
		return false
	}
}

// Defines values for StreamLessonPlanEventPhaseEvent.
const (
	StreamLessonPlanEventPhaseEventPhase StreamLessonPlanEventPhaseEvent = "phase"
)

// Valid indicates whether the value is a known member of the StreamLessonPlanEventPhaseEvent enum.
func (e StreamLessonPlanEventPhaseEvent) Valid() bool {
	switch e {
	case StreamLessonPlanEventPhaseEventPhase:
		return true
	default:
		return false
	}
}

// Defines values for StreamLessonPlanEventResultEvent.
const (
	StreamLessonPlanEventResultEventResult StreamLessonPlanEventResultEvent = "result"
)

// Valid indicates whether the value is a known member of the StreamLessonPlanEventResultEvent enum.
func (e StreamLessonPlanEventResultEvent) Valid() bool {
	switch e {
	case StreamLessonPlanEventResultEventResult:
		return true
	default:
		return false
	}
}

// Defines values for StreamLessonPlanEventStartedEvent.
const (
	StreamLessonPlanEventStartedEventStarted StreamLessonPlanEventStartedEvent = "started"
)

// Valid indicates whether the value is a known member of the StreamLessonPlanEventStartedEvent enum.
func (e StreamLessonPlanEventStartedEvent) Valid() bool {
	switch e {
	case StreamLessonPlanEventStartedEventStarted:
		return true
	default:
		return false
	}
}

// Defines values for TurnRole.
const (
	TurnRoleAssistant TurnRole = "assistant"
	TurnRoleUser      TurnRole = "user"
)

// Valid indicates whether the value is a known member of the TurnRole enum.
func (e TurnRole) Valid() bool {
	switch e {
	case TurnRoleAssistant:
		return true
	case TurnRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for VersionState.
const (
	VersionStateDeprecated   VersionState = "deprecated"
	VersionStateDevelopment  VersionState = "development"
	VersionStateDiscontinued VersionState = "discontinued"
	VersionStateLts          VersionState = "lts"
	VersionStateSupported    VersionState = "supported"
)

// Valid indicates whether the value is a known member of the VersionState enum.
func (e VersionState) Valid() bool {
	switch e {
	case VersionStateDeprecated:
		return true
	case VersionStateDevelopment:
		return true
	case VersionStateDiscontinued:
		return true
	case VersionStateLts:
		return true
	case VersionStateSupported:
		return true
	default:
		return false
	}
}

// AllowanceRow defines model for AllowanceRow.
type AllowanceRow struct {
	Feature   string `json:"feature"`
	Limit     uint32 `json:"limit"`
	Remaining uint32 `json:"remaining"`
	ResetAt   *int64 `json:"reset_at,omitempty"`
	Used      uint32 `json:"used"`
	Window    string `json:"window"`
}

// CreateLessonPlanEventError defines model for CreateLessonPlanEventError.
type CreateLessonPlanEventError struct {
	Data  StreamError                     `json:"data"`
	Event CreateLessonPlanEventErrorEvent `json:"event"`
}

// CreateLessonPlanEventErrorEvent defines model for CreateLessonPlanEventError.Event.
type CreateLessonPlanEventErrorEvent string

// CreateLessonPlanEventPhase defines model for CreateLessonPlanEventPhase.
type CreateLessonPlanEventPhase struct {
	Data  PlanPhase                       `json:"data"`
	Event CreateLessonPlanEventPhaseEvent `json:"event"`
}

// CreateLessonPlanEventPhaseEvent defines model for CreateLessonPlanEventPhase.Event.
type CreateLessonPlanEventPhaseEvent string

// CreateLessonPlanEventResult defines model for CreateLessonPlanEventResult.
type CreateLessonPlanEventResult struct {
	Data  PlanResult                       `json:"data"`
	Event CreateLessonPlanEventResultEvent `json:"event"`
}

// CreateLessonPlanEventResultEvent defines model for CreateLessonPlanEventResult.Event.
type CreateLessonPlanEventResultEvent string

// CreateLessonPlanEventStarted defines model for CreateLessonPlanEventStarted.
type CreateLessonPlanEventStarted struct {
	Data  PlanStarted                       `json:"data"`
	Event CreateLessonPlanEventStartedEvent `json:"event"`
}

// CreateLessonPlanEventStartedEvent defines model for CreateLessonPlanEventStarted.Event.
type CreateLessonPlanEventStartedEvent string

// Done defines model for Done.
type Done = map[string]interface{}

// ErrorEnvelope defines model for Error.
type ErrorEnvelope struct {
	// Code Why the request was refused, as a stable code to branch on: for example `insufficient_scope` (`403`), `rate_limited` (`429`) and, for a metered client, `spend_cap_reached` (`402`) and `metered_billing_inactive` (`402`).
	Code  string `json:"code"`
	Error string `json:"error"`
}

// GenerateVocabularyEventDone defines model for GenerateVocabularyEventDone.
type GenerateVocabularyEventDone struct {
	Data  Done                             `json:"data"`
	Event GenerateVocabularyEventDoneEvent `json:"event"`
}

// GenerateVocabularyEventDoneEvent defines model for GenerateVocabularyEventDone.Event.
type GenerateVocabularyEventDoneEvent string

// GenerateVocabularyEventError defines model for GenerateVocabularyEventError.
type GenerateVocabularyEventError struct {
	Data  StreamError                       `json:"data"`
	Event GenerateVocabularyEventErrorEvent `json:"event"`
}

// GenerateVocabularyEventErrorEvent defines model for GenerateVocabularyEventError.Event.
type GenerateVocabularyEventErrorEvent string

// GenerateVocabularyEventItem defines model for GenerateVocabularyEventItem.
type GenerateVocabularyEventItem struct {
	Data  VocabItem                        `json:"data"`
	Event GenerateVocabularyEventItemEvent `json:"event"`
}

// GenerateVocabularyEventItemEvent defines model for GenerateVocabularyEventItem.Event.
type GenerateVocabularyEventItemEvent string

// GenerateVocabularyEventStarted defines model for GenerateVocabularyEventStarted.
type GenerateVocabularyEventStarted struct {
	Data  VocabStarted                        `json:"data"`
	Event GenerateVocabularyEventStartedEvent `json:"event"`
}

// GenerateVocabularyEventStartedEvent defines model for GenerateVocabularyEventStarted.Event.
type GenerateVocabularyEventStartedEvent string

// LessonPlan defines model for LessonPlan.
type LessonPlan struct {
	AiGenerated bool               `json:"ai_generated"`
	CompletedAt *time.Time         `json:"completed_at,omitempty"`
	Content     *LessonPlanContent `json:"content,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	ID          string             `json:"id"`
	Level       uint8              `json:"level"`
	SourceLang  string             `json:"source_lang"`
	Status      PlanStatus         `json:"status"`
	TargetLang  string             `json:"target_lang"`
	Title       *string            `json:"title,omitempty"`
}

// LessonPlanContent defines model for LessonPlanContent.
type LessonPlanContent struct {
	Introduction       *string    `json:"introduction,omitempty"`
	LearningObjectives []string   `json:"learning_objectives"`
	Sets               []PlanSet  `json:"sets"`
	Vocabulary         []PlanWord `json:"vocabulary"`
}

// LessonPlanCreateRequest defines model for LessonPlanCreateRequest.
type LessonPlanCreateRequest struct {
	Context    string `json:"context"`
	Level      uint8  `json:"level"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}

// Notice defines model for Notice.
type Notice struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PlanPending defines model for PlanPending.
type PlanPending struct {
	PlanID string     `json:"plan_id"`
	Status PlanStatus `json:"status"`
}

// PlanPhase defines model for PlanPhase.
type PlanPhase struct {
	Attempt uint8  `json:"attempt"`
	Phase   string `json:"phase"`
}

// PlanQuestion defines model for PlanQuestion.
type PlanQuestion struct {
	Answer      string    `json:"answer"`
	Explanation string    `json:"explanation"`
	Hint        *string   `json:"hint,omitempty"`
	Options     *[]string `json:"options,omitempty"`
	Prompt      string    `json:"prompt"`
	Type        string    `json:"type"`
}

// PlanResult defines model for PlanResult.
type PlanResult struct {
	Plan LessonPlan `json:"plan"`
}

// PlanSet defines model for PlanSet.
type PlanSet struct {
	Context   *string        `json:"context,omitempty"`
	Number    uint8          `json:"number"`
	Questions []PlanQuestion `json:"questions"`
}

// PlanStarted defines model for PlanStarted.
type PlanStarted struct {
	PlanID string `json:"plan_id"`
}

// PlanStatus defines model for PlanStatus.
type PlanStatus string

// PlanWord defines model for PlanWord.
type PlanWord struct {
	Pronunciation *string `json:"pronunciation,omitempty"`
	Translation   string  `json:"translation"`
	Word          string  `json:"word"`
}

// SendTutorMessageEventDelta defines model for SendTutorMessageEventDelta.
type SendTutorMessageEventDelta struct {
	Data  TurnDelta                       `json:"data"`
	Event SendTutorMessageEventDeltaEvent `json:"event"`
}

// SendTutorMessageEventDeltaEvent defines model for SendTutorMessageEventDelta.Event.
type SendTutorMessageEventDeltaEvent string

// SendTutorMessageEventDone defines model for SendTutorMessageEventDone.
type SendTutorMessageEventDone struct {
	Data  Done                           `json:"data"`
	Event SendTutorMessageEventDoneEvent `json:"event"`
}

// SendTutorMessageEventDoneEvent defines model for SendTutorMessageEventDone.Event.
type SendTutorMessageEventDoneEvent string

// SendTutorMessageEventError defines model for SendTutorMessageEventError.
type SendTutorMessageEventError struct {
	Data  StreamError                     `json:"data"`
	Event SendTutorMessageEventErrorEvent `json:"event"`
}

// SendTutorMessageEventErrorEvent defines model for SendTutorMessageEventError.Event.
type SendTutorMessageEventErrorEvent string

// SendTutorMessageEventNotice defines model for SendTutorMessageEventNotice.
type SendTutorMessageEventNotice struct {
	Data  Notice                           `json:"data"`
	Event SendTutorMessageEventNoticeEvent `json:"event"`
}

// SendTutorMessageEventNoticeEvent defines model for SendTutorMessageEventNotice.Event.
type SendTutorMessageEventNoticeEvent string

// StreamError defines model for StreamError.
type StreamError struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	PlanID  *string `json:"plan_id,omitempty"`
}

// StreamLessonPlanEventError defines model for StreamLessonPlanEventError.
type StreamLessonPlanEventError struct {
	Data  StreamError                     `json:"data"`
	Event StreamLessonPlanEventErrorEvent `json:"event"`
}

// StreamLessonPlanEventErrorEvent defines model for StreamLessonPlanEventError.Event.
type StreamLessonPlanEventErrorEvent string

// StreamLessonPlanEventPending defines model for StreamLessonPlanEventPending.
type StreamLessonPlanEventPending struct {
	Data  PlanPending                       `json:"data"`
	Event StreamLessonPlanEventPendingEvent `json:"event"`
}

// StreamLessonPlanEventPendingEvent defines model for StreamLessonPlanEventPending.Event.
type StreamLessonPlanEventPendingEvent string

// StreamLessonPlanEventPhase defines model for StreamLessonPlanEventPhase.
type StreamLessonPlanEventPhase struct {
	Data  PlanPhase                       `json:"data"`
	Event StreamLessonPlanEventPhaseEvent `json:"event"`
}

// StreamLessonPlanEventPhaseEvent defines model for StreamLessonPlanEventPhase.Event.
type StreamLessonPlanEventPhaseEvent string

// StreamLessonPlanEventResult defines model for StreamLessonPlanEventResult.
type StreamLessonPlanEventResult struct {
	Data  PlanResult                       `json:"data"`
	Event StreamLessonPlanEventResultEvent `json:"event"`
}

// StreamLessonPlanEventResultEvent defines model for StreamLessonPlanEventResult.Event.
type StreamLessonPlanEventResultEvent string

// StreamLessonPlanEventStarted defines model for StreamLessonPlanEventStarted.
type StreamLessonPlanEventStarted struct {
	Data  PlanStarted                       `json:"data"`
	Event StreamLessonPlanEventStartedEvent `json:"event"`
}

// StreamLessonPlanEventStartedEvent defines model for StreamLessonPlanEventStarted.Event.
type StreamLessonPlanEventStartedEvent string

// TurnDelta defines model for TurnDelta.
type TurnDelta struct {
	Text string `json:"text"`
}

// TurnEntry defines model for TurnEntry.
type TurnEntry struct {
	Content string   `json:"content"`
	Role    TurnRole `json:"role"`
}

// TurnRole defines model for TurnRole.
type TurnRole string

// TutorTurnRequest defines model for TutorTurnRequest.
type TutorTurnRequest struct {
	Character  *string      `json:"character,omitempty"`
	History    *[]TurnEntry `json:"history,omitempty"`
	Level      *uint8       `json:"level,omitempty"`
	Message    string       `json:"message"`
	Situation  *string      `json:"situation,omitempty"`
	SourceLang string       `json:"source_lang"`
	TargetLang string       `json:"target_lang"`
}

// Usage defines model for Usage.
type Usage struct {
	Allowance []AllowanceRow `json:"allowance"`

	// Ledger This client's calls and units since midnight UTC on the first of the month. Present only for a metered client, whose calls spend no allowance. It can trail your latest call by up to five seconds.
	Ledger *UsageLedger `json:"ledger,omitempty"`
}

// UsageLedger defines model for UsageLedger.
type UsageLedger struct {
	Calls uint64    `json:"calls"`
	Since time.Time `json:"since"`
	Units uint64    `json:"units"`
}

// VersionDetail defines model for VersionDetail.
type VersionDetail struct {
	History  []VersionHistoryEntry `json:"history"`
	ID       string                `json:"id"`
	Lts      bool                  `json:"lts"`
	MintedAt time.Time             `json:"minted_at"`
	Spec     VersionSpec           `json:"spec"`
	State    VersionState          `json:"state"`
	Summary  *string               `json:"summary"`
	SunsetAt *time.Time            `json:"sunset_at"`
}

// VersionHistoryEntry defines model for VersionHistoryEntry.
type VersionHistoryEntry struct {
	At    time.Time    `json:"at"`
	State VersionState `json:"state"`
}

// VersionList defines model for VersionList.
type VersionList struct {
	Current     *string          `json:"current"`
	Development *string          `json:"development"`
	Versions    []VersionSummary `json:"versions"`
}

// VersionSpec defines model for VersionSpec.
type VersionSpec struct {
	Sha256 *string `json:"sha256"`
	URL    string  `json:"url"`
}

// VersionState defines model for VersionState.
type VersionState string

// VersionSummary defines model for VersionSummary.
type VersionSummary struct {
	ID       string       `json:"id"`
	Lts      bool         `json:"lts"`
	MintedAt time.Time    `json:"minted_at"`
	State    VersionState `json:"state"`
	SunsetAt *time.Time   `json:"sunset_at"`
}

// VocabExample defines model for VocabExample.
type VocabExample struct {
	Sentence    string `json:"sentence"`
	Translation string `json:"translation"`
}

// VocabItem defines model for VocabItem.
type VocabItem struct {
	Example       *VocabExample `json:"example,omitempty"`
	ImageURL      *string       `json:"image_url,omitempty"`
	Pronunciation *string       `json:"pronunciation,omitempty"`
	Reading       *string       `json:"reading,omitempty"`
	Translation   string        `json:"translation"`
	Word          string        `json:"word"`
}

// VocabMeta defines model for VocabMeta.
type VocabMeta struct {
	AiGenerated bool   `json:"ai_generated"`
	Count       uint32 `json:"count"`
	Framework   string `json:"framework"`
	Level       uint8  `json:"level"`
	SourceLang  string `json:"source_lang"`
	TargetLang  string `json:"target_lang"`
}

// VocabRequest defines model for VocabRequest.
type VocabRequest struct {
	Count      *uint8 `json:"count,omitempty"`
	Level      uint8  `json:"level"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}

// VocabStarted defines model for VocabStarted.
type VocabStarted struct {
	Meta VocabMeta `json:"meta"`
}

// LingaraVersion defines model for LingaraVersion.
type LingaraVersion = string

// PlanID defines model for PlanId.
type PlanID = string

// VersionID defines model for VersionId.
type VersionID = string

// ErrorResponse defines model for Error.
type ErrorResponse = ErrorEnvelope

// PaymentRequired defines model for PaymentRequired.
type PaymentRequired = ErrorEnvelope

// Unavailable defines model for Unavailable.
type Unavailable = ErrorEnvelope

// VersionDiscontinued defines model for VersionDiscontinued.
type VersionDiscontinued = ErrorEnvelope

// GetLessonPlanParams defines parameters for GetLessonPlan.
type GetLessonPlanParams struct {
	// LingaraVersion The API version to answer this request under. Without it, an access token gets the version its client is pinned to, and a request with no token gets the current version. The version still in development is reached only by naming it here. An unknown version answers `400` with code `api_version_unknown`. `GET /v1/versions` lists the versions.
	LingaraVersion *LingaraVersion `json:"Lingara-Version,omitempty"`
}

// GetOpenAPIDocumentParams defines parameters for GetOpenAPIDocument.
type GetOpenAPIDocumentParams struct {
	// LingaraVersion The API version to answer this request under. Without it, an access token gets the version its client is pinned to, and a request with no token gets the current version. The version still in development is reached only by naming it here. An unknown version answers `400` with code `api_version_unknown`. `GET /v1/versions` lists the versions.
	LingaraVersion *LingaraVersion `json:"Lingara-Version,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	// LingaraVersion The API version to answer this request under. Without it, an access token gets the version its client is pinned to, and a request with no token gets the current version. The version still in development is reached only by naming it here. An unknown version answers `400` with code `api_version_unknown`. `GET /v1/versions` lists the versions.
	LingaraVersion *LingaraVersion `json:"Lingara-Version,omitempty"`
}

// ListAPIVersionsParams defines parameters for ListAPIVersions.
type ListAPIVersionsParams struct {
	// LingaraVersion The API version to answer this request under. Without it, an access token gets the version its client is pinned to, and a request with no token gets the current version. The version still in development is reached only by naming it here. An unknown version answers `400` with code `api_version_unknown`. `GET /v1/versions` lists the versions.
	LingaraVersion *LingaraVersion `json:"Lingara-Version,omitempty"`
}

// GetAPIVersionParams defines parameters for GetAPIVersion.
type GetAPIVersionParams struct {
	// LingaraVersion The API version to answer this request under. Without it, an access token gets the version its client is pinned to, and a request with no token gets the current version. The version still in development is reached only by naming it here. An unknown version answers `400` with code `api_version_unknown`. `GET /v1/versions` lists the versions.
	LingaraVersion *LingaraVersion `json:"Lingara-Version,omitempty"`
}
