// Code generated by go/codegen from the generator view (spec/generator/openapi.3.0.json). DO NOT EDIT.

package lingara

// routes is every operation's method and path, keyed by operationId: from
// paths for a JSON operation and from x-lingara-streams for a stream.
var routes = map[string]route{
	"createLessonPlan": {method: "POST", path: "/v1/lesson-plans", needsToken: true,
		stream: &streamRoute{requestBody: "LessonPlanCreateRequest", events: []string{"started", "phase", "result", "error"}, ends: map[string]ending{"result": endYield, "error": endRaise}}},
	"generateVocabulary": {method: "POST", path: "/v1/vocab/stream", needsToken: true,
		stream: &streamRoute{requestBody: "VocabRequest", events: []string{"started", "item", "done", "error"}, ends: map[string]ending{"done": endQuiet, "error": endRaise}}},
	"getApiVersion":      {method: "GET", path: "/v1/versions/{id}", needsToken: false},
	"getLessonPlan":      {method: "GET", path: "/v1/lesson-plans/{id}", needsToken: true},
	"getOpenApiDocument": {method: "GET", path: "/v1/openapi.json", needsToken: false},
	"getUsage":           {method: "GET", path: "/v1/usage", needsToken: true},
	"listApiVersions":    {method: "GET", path: "/v1/versions", needsToken: false},
	"sendTutorMessage": {method: "POST", path: "/v1/tutor/message", needsToken: true,
		stream: &streamRoute{requestBody: "TutorTurnRequest", events: []string{"delta", "notice", "done", "error"}, ends: map[string]ending{"done": endQuiet, "error": endRaise}}},
	"streamLessonPlan": {method: "GET", path: "/v1/lesson-plans/{id}/stream", needsToken: true,
		stream: &streamRoute{requestBody: "", events: []string{"started", "phase", "result", "pending", "error"}, ends: map[string]ending{"result": endYield, "pending": endYield, "error": endRaise}}},
}
