// Code generated by go/codegen from the generator view (spec/generator/openapi.3.0.json). DO NOT EDIT.

package lingara

import "encoding/json"

// CreateLessonPlanEvent is one event of createLessonPlan's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type CreateLessonPlanEvent interface{ isCreateLessonPlanEvent() }

func (CreateLessonPlanEventStarted) isCreateLessonPlanEvent() {}
func (CreateLessonPlanEventPhase) isCreateLessonPlanEvent()   {}
func (CreateLessonPlanEventResult) isCreateLessonPlanEvent()  {}
func (CreateLessonPlanEventError) isCreateLessonPlanEvent()   {}

func decodeCreateLessonPlanEvent(name string, frame []byte) (CreateLessonPlanEvent, bool, error) {
	switch name {
	case "started":
		var e CreateLessonPlanEventStarted
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "phase":
		var e CreateLessonPlanEventPhase
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "result":
		var e CreateLessonPlanEventResult
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e CreateLessonPlanEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}

// GenerateVocabularyEvent is one event of generateVocabulary's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type GenerateVocabularyEvent interface{ isGenerateVocabularyEvent() }

func (GenerateVocabularyEventStarted) isGenerateVocabularyEvent() {}
func (GenerateVocabularyEventItem) isGenerateVocabularyEvent()    {}
func (GenerateVocabularyEventDone) isGenerateVocabularyEvent()    {}
func (GenerateVocabularyEventError) isGenerateVocabularyEvent()   {}

func decodeGenerateVocabularyEvent(name string, frame []byte) (GenerateVocabularyEvent, bool, error) {
	switch name {
	case "started":
		var e GenerateVocabularyEventStarted
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "item":
		var e GenerateVocabularyEventItem
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "done":
		var e GenerateVocabularyEventDone
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e GenerateVocabularyEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}

// SendDialogueTurnEvent is one event of sendDialogueTurn's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type SendDialogueTurnEvent interface{ isSendDialogueTurnEvent() }

func (SendDialogueTurnEventDelta) isSendDialogueTurnEvent()  {}
func (SendDialogueTurnEventNotice) isSendDialogueTurnEvent() {}
func (SendDialogueTurnEventDone) isSendDialogueTurnEvent()   {}
func (SendDialogueTurnEventError) isSendDialogueTurnEvent()  {}

func decodeSendDialogueTurnEvent(name string, frame []byte) (SendDialogueTurnEvent, bool, error) {
	switch name {
	case "delta":
		var e SendDialogueTurnEventDelta
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "notice":
		var e SendDialogueTurnEventNotice
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "done":
		var e SendDialogueTurnEventDone
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e SendDialogueTurnEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}

// SendTutorMessageEvent is one event of sendTutorMessage's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type SendTutorMessageEvent interface{ isSendTutorMessageEvent() }

func (SendTutorMessageEventDelta) isSendTutorMessageEvent()  {}
func (SendTutorMessageEventNotice) isSendTutorMessageEvent() {}
func (SendTutorMessageEventDone) isSendTutorMessageEvent()   {}
func (SendTutorMessageEventError) isSendTutorMessageEvent()  {}

func decodeSendTutorMessageEvent(name string, frame []byte) (SendTutorMessageEvent, bool, error) {
	switch name {
	case "delta":
		var e SendTutorMessageEventDelta
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "notice":
		var e SendTutorMessageEventNotice
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "done":
		var e SendTutorMessageEventDone
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e SendTutorMessageEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}

// StreamEventsEvent is one event of streamEvents's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type StreamEventsEvent interface{ isStreamEventsEvent() }

func (StreamEventsEventEvent) isStreamEventsEvent() {}
func (StreamEventsEventDone) isStreamEventsEvent()  {}
func (StreamEventsEventError) isStreamEventsEvent() {}

func decodeStreamEventsEvent(name string, frame []byte) (StreamEventsEvent, bool, error) {
	switch name {
	case "event":
		var e StreamEventsEventEvent
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "done":
		var e StreamEventsEventDone
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e StreamEventsEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}

// StreamLessonPlanEvent is one event of streamLessonPlan's stream: type-switch on its
// concrete branch. The error branch, and a Done-bodied one, are never yielded.
type StreamLessonPlanEvent interface{ isStreamLessonPlanEvent() }

func (StreamLessonPlanEventStarted) isStreamLessonPlanEvent() {}
func (StreamLessonPlanEventPhase) isStreamLessonPlanEvent()   {}
func (StreamLessonPlanEventResult) isStreamLessonPlanEvent()  {}
func (StreamLessonPlanEventPending) isStreamLessonPlanEvent() {}
func (StreamLessonPlanEventError) isStreamLessonPlanEvent()   {}

func decodeStreamLessonPlanEvent(name string, frame []byte) (StreamLessonPlanEvent, bool, error) {
	switch name {
	case "started":
		var e StreamLessonPlanEventStarted
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "phase":
		var e StreamLessonPlanEventPhase
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "result":
		var e StreamLessonPlanEventResult
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "pending":
		var e StreamLessonPlanEventPending
		err := json.Unmarshal(frame, &e)
		return e, true, err
	case "error":
		var e StreamLessonPlanEventError
		err := json.Unmarshal(frame, &e)
		return e, true, err
	}
	return nil, false, nil
}
