<?php

// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.

declare(strict_types=1);

namespace Lingara\Stream\StreamEventsEvent;

/** The `event` event: its payload is `$data`. */
final readonly class Event implements \Lingara\Stream\StreamEventsEvent
{
    // Fully qualified: an event may share its short name with its
    // payload's model (`notice` carries a Notice).
    public function __construct(public \Lingara\Model\EventEnvelope $data)
    {
    }
}
