<?php
/**
 * AllowanceRow
 *
 * PHP version 8.1
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lingara API
 *
 * Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.
 *
 * The version of the OpenAPI document: 2026-10-affable-towhee
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lingara\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Lingara\ObjectSerializer;

/**
 * AllowanceRow Class Doc Comment
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AllowanceRow implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'AllowanceRow';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'feature' => 'string',
        'window' => 'string',
        'limit' => 'int',
        'used' => 'int',
        'remaining' => 'int',
        'reset_at' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'feature' => null,
        'window' => null,
        'limit' => 'uint32',
        'used' => 'uint32',
        'remaining' => 'uint32',
        'reset_at' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'feature' => false,
        'window' => false,
        'limit' => false,
        'used' => false,
        'remaining' => false,
        'reset_at' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'feature' => 'feature',
        'window' => 'window',
        'limit' => 'limit',
        'used' => 'used',
        'remaining' => 'remaining',
        'reset_at' => 'reset_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'feature' => 'setFeature',
        'window' => 'setWindow',
        'limit' => 'setLimit',
        'used' => 'setUsed',
        'remaining' => 'setRemaining',
        'reset_at' => 'setResetAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'feature' => 'getFeature',
        'window' => 'getWindow',
        'limit' => 'getLimit',
        'used' => 'getUsed',
        'remaining' => 'getRemaining',
        'reset_at' => 'getResetAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('feature', $data ?? [], null);
        $this->setIfExists('window', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], null);
        $this->setIfExists('used', $data ?? [], null);
        $this->setIfExists('remaining', $data ?? [], null);
        $this->setIfExists('reset_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['feature'] === null) {
            $invalidProperties[] = "'feature' can't be null";
        }
        if ($this->container['window'] === null) {
            $invalidProperties[] = "'window' can't be null";
        }
        if ($this->container['limit'] === null) {
            $invalidProperties[] = "'limit' can't be null";
        }
        if (($this->container['limit'] < 0)) {
            $invalidProperties[] = "invalid value for 'limit', must be bigger than or equal to 0.";
        }

        if ($this->container['used'] === null) {
            $invalidProperties[] = "'used' can't be null";
        }
        if (($this->container['used'] < 0)) {
            $invalidProperties[] = "invalid value for 'used', must be bigger than or equal to 0.";
        }

        if ($this->container['remaining'] === null) {
            $invalidProperties[] = "'remaining' can't be null";
        }
        if (($this->container['remaining'] < 0)) {
            $invalidProperties[] = "invalid value for 'remaining', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets feature
     *
     * @return string
     */
    public function getFeature(): string
    {
        return $this->container['feature'];
    }

    /**
     * Sets feature
     *
     * @param string $feature feature
     *
     * @return $this
     */
    public function setFeature(string $feature): static
    {
        if (is_null($feature)) {
            throw new InvalidArgumentException('non-nullable feature cannot be null');
        }
        $this->container['feature'] = $feature;

        return $this;
    }

    /**
     * Gets window
     *
     * @return string
     */
    public function getWindow(): string
    {
        return $this->container['window'];
    }

    /**
     * Sets window
     *
     * @param string $window window
     *
     * @return $this
     */
    public function setWindow(string $window): static
    {
        if (is_null($window)) {
            throw new InvalidArgumentException('non-nullable window cannot be null');
        }
        $this->container['window'] = $window;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int
     */
    public function getLimit(): int
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int $limit limit
     *
     * @return $this
     */
    public function setLimit(int $limit): static
    {
        if (is_null($limit)) {
            throw new InvalidArgumentException('non-nullable limit cannot be null');
        }

        if (($limit < 0)) {
            throw new InvalidArgumentException('invalid value for $limit when calling AllowanceRow., must be bigger than or equal to 0.');
        }

        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets used
     *
     * @return int
     */
    public function getUsed(): int
    {
        return $this->container['used'];
    }

    /**
     * Sets used
     *
     * @param int $used used
     *
     * @return $this
     */
    public function setUsed(int $used): static
    {
        if (is_null($used)) {
            throw new InvalidArgumentException('non-nullable used cannot be null');
        }

        if (($used < 0)) {
            throw new InvalidArgumentException('invalid value for $used when calling AllowanceRow., must be bigger than or equal to 0.');
        }

        $this->container['used'] = $used;

        return $this;
    }

    /**
     * Gets remaining
     *
     * @return int
     */
    public function getRemaining(): int
    {
        return $this->container['remaining'];
    }

    /**
     * Sets remaining
     *
     * @param int $remaining remaining
     *
     * @return $this
     */
    public function setRemaining(int $remaining): static
    {
        if (is_null($remaining)) {
            throw new InvalidArgumentException('non-nullable remaining cannot be null');
        }

        if (($remaining < 0)) {
            throw new InvalidArgumentException('invalid value for $remaining when calling AllowanceRow., must be bigger than or equal to 0.');
        }

        $this->container['remaining'] = $remaining;

        return $this;
    }

    /**
     * Gets reset_at
     *
     * @return int|null
     */
    public function getResetAt(): ?int
    {
        return $this->container['reset_at'];
    }

    /**
     * Sets reset_at
     *
     * @param int|null $reset_at reset_at
     *
     * @return $this
     */
    public function setResetAt(?int $reset_at): static
    {
        if (is_null($reset_at)) {
            array_push($this->openAPINullablesSetToNull, 'reset_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reset_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reset_at'] = $reset_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


