<?php
/**
 * DialogueTurnRequest
 *
 * PHP version 8.1
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lingara API
 *
 * Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.
 *
 * The version of the OpenAPI document: 2026-10-golden-remora
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lingara\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Lingara\ObjectSerializer;

/**
 * DialogueTurnRequest Class Doc Comment
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class DialogueTurnRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'DialogueTurnRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'npc' => '\Lingara\Model\Npc',
        'scene' => 'string',
        'source_lang' => 'string',
        'target_lang' => 'string',
        'level' => 'int',
        'line' => 'string',
        'history' => '\Lingara\Model\DialogueEntry[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'npc' => null,
        'scene' => null,
        'source_lang' => null,
        'target_lang' => null,
        'level' => 'uint8',
        'line' => null,
        'history' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'npc' => false,
        'scene' => true,
        'source_lang' => false,
        'target_lang' => false,
        'level' => false,
        'line' => false,
        'history' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'npc' => 'npc',
        'scene' => 'scene',
        'source_lang' => 'source_lang',
        'target_lang' => 'target_lang',
        'level' => 'level',
        'line' => 'line',
        'history' => 'history'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'npc' => 'setNpc',
        'scene' => 'setScene',
        'source_lang' => 'setSourceLang',
        'target_lang' => 'setTargetLang',
        'level' => 'setLevel',
        'line' => 'setLine',
        'history' => 'setHistory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'npc' => 'getNpc',
        'scene' => 'getScene',
        'source_lang' => 'getSourceLang',
        'target_lang' => 'getTargetLang',
        'level' => 'getLevel',
        'line' => 'getLine',
        'history' => 'getHistory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('npc', $data ?? [], null);
        $this->setIfExists('scene', $data ?? [], null);
        $this->setIfExists('source_lang', $data ?? [], null);
        $this->setIfExists('target_lang', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('line', $data ?? [], null);
        $this->setIfExists('history', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['npc'] === null) {
            $invalidProperties[] = "'npc' can't be null";
        }
        if (!is_null($this->container['scene']) && (mb_strlen($this->container['scene']) > 160)) {
            $invalidProperties[] = "invalid value for 'scene', the character length must be smaller than or equal to 160.";
        }

        if (!is_null($this->container['scene']) && (mb_strlen($this->container['scene']) < 1)) {
            $invalidProperties[] = "invalid value for 'scene', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['source_lang'] === null) {
            $invalidProperties[] = "'source_lang' can't be null";
        }
        if ($this->container['target_lang'] === null) {
            $invalidProperties[] = "'target_lang' can't be null";
        }
        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if (($this->container['level'] > 9)) {
            $invalidProperties[] = "invalid value for 'level', must be smaller than or equal to 9.";
        }

        if (($this->container['level'] < 1)) {
            $invalidProperties[] = "invalid value for 'level', must be bigger than or equal to 1.";
        }

        if ($this->container['line'] === null) {
            $invalidProperties[] = "'line' can't be null";
        }
        if ((mb_strlen($this->container['line']) > 500)) {
            $invalidProperties[] = "invalid value for 'line', the character length must be smaller than or equal to 500.";
        }

        if ((mb_strlen($this->container['line']) < 1)) {
            $invalidProperties[] = "invalid value for 'line', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['history']) && (count($this->container['history']) > 12)) {
            $invalidProperties[] = "invalid value for 'history', number of items must be less than or equal to 12.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets npc
     *
     * @return \Lingara\Model\Npc
     */
    public function getNpc(): \Lingara\Model\Npc
    {
        return $this->container['npc'];
    }

    /**
     * Sets npc
     *
     * @param \Lingara\Model\Npc $npc npc
     *
     * @return $this
     */
    public function setNpc(\Lingara\Model\Npc $npc): static
    {
        if (is_null($npc)) {
            throw new InvalidArgumentException('non-nullable npc cannot be null');
        }
        $this->container['npc'] = $npc;

        return $this;
    }

    /**
     * Gets scene
     *
     * @return string|null
     */
    public function getScene(): ?string
    {
        return $this->container['scene'];
    }

    /**
     * Sets scene
     *
     * @param string|null $scene scene
     *
     * @return $this
     */
    public function setScene(?string $scene): static
    {
        if (is_null($scene)) {
            array_push($this->openAPINullablesSetToNull, 'scene');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scene', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($scene) && (mb_strlen($scene) > 160)) {
            throw new InvalidArgumentException('invalid length for $scene when calling DialogueTurnRequest., must be smaller than or equal to 160.');
        }
        if (!is_null($scene) && (mb_strlen($scene) < 1)) {
            throw new InvalidArgumentException('invalid length for $scene when calling DialogueTurnRequest., must be bigger than or equal to 1.');
        }

        $this->container['scene'] = $scene;

        return $this;
    }

    /**
     * Gets source_lang
     *
     * @return string
     */
    public function getSourceLang(): string
    {
        return $this->container['source_lang'];
    }

    /**
     * Sets source_lang
     *
     * @param string $source_lang source_lang
     *
     * @return $this
     */
    public function setSourceLang(string $source_lang): static
    {
        if (is_null($source_lang)) {
            throw new InvalidArgumentException('non-nullable source_lang cannot be null');
        }
        $this->container['source_lang'] = $source_lang;

        return $this;
    }

    /**
     * Gets target_lang
     *
     * @return string
     */
    public function getTargetLang(): string
    {
        return $this->container['target_lang'];
    }

    /**
     * Sets target_lang
     *
     * @param string $target_lang target_lang
     *
     * @return $this
     */
    public function setTargetLang(string $target_lang): static
    {
        if (is_null($target_lang)) {
            throw new InvalidArgumentException('non-nullable target_lang cannot be null');
        }
        $this->container['target_lang'] = $target_lang;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int
     */
    public function getLevel(): int
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int $level level
     *
     * @return $this
     */
    public function setLevel(int $level): static
    {
        if (is_null($level)) {
            throw new InvalidArgumentException('non-nullable level cannot be null');
        }

        if (($level > 9)) {
            throw new InvalidArgumentException('invalid value for $level when calling DialogueTurnRequest., must be smaller than or equal to 9.');
        }
        if (($level < 1)) {
            throw new InvalidArgumentException('invalid value for $level when calling DialogueTurnRequest., must be bigger than or equal to 1.');
        }

        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets line
     *
     * @return string
     */
    public function getLine(): string
    {
        return $this->container['line'];
    }

    /**
     * Sets line
     *
     * @param string $line line
     *
     * @return $this
     */
    public function setLine(string $line): static
    {
        if (is_null($line)) {
            throw new InvalidArgumentException('non-nullable line cannot be null');
        }
        if ((mb_strlen($line) > 500)) {
            throw new InvalidArgumentException('invalid length for $line when calling DialogueTurnRequest., must be smaller than or equal to 500.');
        }
        if ((mb_strlen($line) < 1)) {
            throw new InvalidArgumentException('invalid length for $line when calling DialogueTurnRequest., must be bigger than or equal to 1.');
        }

        $this->container['line'] = $line;

        return $this;
    }

    /**
     * Gets history
     *
     * @return \Lingara\Model\DialogueEntry[]|null
     */
    public function getHistory(): ?array
    {
        return $this->container['history'];
    }

    /**
     * Sets history
     *
     * @param \Lingara\Model\DialogueEntry[]|null $history The conversation so far, oldest first, at most 12 lines. You keep the window: Lingara stores nothing between turns. Send each NPC reply back cut to its first 500 characters.
     *
     * @return $this
     */
    public function setHistory(?array $history): static
    {
        if (is_null($history)) {
            throw new InvalidArgumentException('non-nullable history cannot be null');
        }

        if ((count($history) > 12)) {
            throw new InvalidArgumentException('invalid value for $history when calling DialogueTurnRequest., number of items must be less than or equal to 12.');
        }
        $this->container['history'] = $history;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


