<?php
/**
 * EmbedTokenRequest
 *
 * PHP version 8.1
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lingara API
 *
 * Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.
 *
 * The version of the OpenAPI document: 2026-10-golden-remora
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lingara\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Lingara\ObjectSerializer;

/**
 * EmbedTokenRequest Class Doc Comment
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EmbedTokenRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'EmbedTokenRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'player_ref' => 'string',
        'scopes' => 'string[]',
        'origin' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'player_ref' => null,
        'scopes' => null,
        'origin' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'player_ref' => false,
        'scopes' => true,
        'origin' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'player_ref' => 'player_ref',
        'scopes' => 'scopes',
        'origin' => 'origin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'player_ref' => 'setPlayerRef',
        'scopes' => 'setScopes',
        'origin' => 'setOrigin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'player_ref' => 'getPlayerRef',
        'scopes' => 'getScopes',
        'origin' => 'getOrigin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const SCOPES_EVENTS_READ = 'events:read';
    public const SCOPES_EVENTS_WRITE = 'events:write';
    public const SCOPES_LESSON_PLANS_READ = 'lesson_plans:read';
    public const SCOPES_LESSON_PLANS_WRITE = 'lesson_plans:write';
    public const SCOPES_EMBED_PLAY = 'embed:play';
    public const SCOPES_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getScopesAllowableValues()
    {
        return [
            self::SCOPES_EVENTS_READ,
            self::SCOPES_EVENTS_WRITE,
            self::SCOPES_LESSON_PLANS_READ,
            self::SCOPES_LESSON_PLANS_WRITE,
            self::SCOPES_EMBED_PLAY,
            self::SCOPES_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('player_ref', $data ?? [], null);
        $this->setIfExists('scopes', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['player_ref'] === null) {
            $invalidProperties[] = "'player_ref' can't be null";
        }
        if ((mb_strlen($this->container['player_ref']) > 128)) {
            $invalidProperties[] = "invalid value for 'player_ref', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['player_ref']) < 1)) {
            $invalidProperties[] = "invalid value for 'player_ref', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['scopes']) && (count($this->container['scopes']) > 5)) {
            $invalidProperties[] = "invalid value for 'scopes', number of items must be less than or equal to 5.";
        }

        if (!is_null($this->container['origin']) && (mb_strlen($this->container['origin']) > 255)) {
            $invalidProperties[] = "invalid value for 'origin', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['origin']) && !preg_match("/^https?:\/\/[^\/?#@ ]+$/", $this->container['origin'])) {
            $invalidProperties[] = "invalid value for 'origin', must be conform to the pattern /^https?:\/\/[^\/?#@ ]+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets player_ref
     *
     * @return string
     */
    public function getPlayerRef(): string
    {
        return $this->container['player_ref'];
    }

    /**
     * Sets player_ref
     *
     * @param string $player_ref Your own reference for the player: 1 to 128 bytes of UTF-8, with no control characters. Lingara stores only a hash of it.
     *
     * @return $this
     */
    public function setPlayerRef(string $player_ref): static
    {
        if (is_null($player_ref)) {
            throw new InvalidArgumentException('non-nullable player_ref cannot be null');
        }
        if ((mb_strlen($player_ref) > 128)) {
            throw new InvalidArgumentException('invalid length for $player_ref when calling EmbedTokenRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($player_ref) < 1)) {
            throw new InvalidArgumentException('invalid length for $player_ref when calling EmbedTokenRequest., must be bigger than or equal to 1.');
        }

        $this->container['player_ref'] = $player_ref;

        return $this;
    }

    /**
     * Gets scopes
     *
     * @return string[]|null
     */
    public function getScopes(): ?array
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param string[]|null $scopes scopes
     *
     * @return $this
     */
    public function setScopes(?array $scopes): static
    {
        if (is_null($scopes)) {
            array_push($this->openAPINullablesSetToNull, 'scopes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scopes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = self::getScopesAllowableValues();
        if (!is_null($scopes) && array_diff($scopes, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'scopes', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if (!is_null($scopes) && (count($scopes) > 5)) {
            throw new InvalidArgumentException('invalid value for $scopes when calling EmbedTokenRequest., number of items must be less than or equal to 5.');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return string|null
     */
    public function getOrigin(): ?string
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param string|null $origin origin
     *
     * @return $this
     */
    public function setOrigin(?string $origin): static
    {
        if (is_null($origin)) {
            array_push($this->openAPINullablesSetToNull, 'origin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('origin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($origin) && (mb_strlen($origin) > 255)) {
            throw new InvalidArgumentException('invalid length for $origin when calling EmbedTokenRequest., must be smaller than or equal to 255.');
        }
        if (!is_null($origin) && (!preg_match("/^https?:\/\/[^\/?#@ ]+$/", ObjectSerializer::toString($origin)))) {
            throw new InvalidArgumentException("invalid value for \$origin when calling EmbedTokenRequest., must conform to the pattern /^https?:\/\/[^\/?#@ ]+$/.");
        }

        $this->container['origin'] = $origin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


