<?php
/**
 * TutorTurnRequest
 *
 * PHP version 8.1
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lingara API
 *
 * Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.
 *
 * The version of the OpenAPI document: 2026-09-glowing-hoatzin
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lingara\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Lingara\ObjectSerializer;

/**
 * TutorTurnRequest Class Doc Comment
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class TutorTurnRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'TutorTurnRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'message' => 'string',
        'history' => '\Lingara\Model\TurnEntry[]',
        'source_lang' => 'string',
        'target_lang' => 'string',
        'level' => 'int',
        'character' => 'string',
        'situation' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'message' => null,
        'history' => null,
        'source_lang' => null,
        'target_lang' => null,
        'level' => 'uint8',
        'character' => null,
        'situation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'message' => false,
        'history' => false,
        'source_lang' => false,
        'target_lang' => false,
        'level' => true,
        'character' => true,
        'situation' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'message' => 'message',
        'history' => 'history',
        'source_lang' => 'source_lang',
        'target_lang' => 'target_lang',
        'level' => 'level',
        'character' => 'character',
        'situation' => 'situation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'message' => 'setMessage',
        'history' => 'setHistory',
        'source_lang' => 'setSourceLang',
        'target_lang' => 'setTargetLang',
        'level' => 'setLevel',
        'character' => 'setCharacter',
        'situation' => 'setSituation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'message' => 'getMessage',
        'history' => 'getHistory',
        'source_lang' => 'getSourceLang',
        'target_lang' => 'getTargetLang',
        'level' => 'getLevel',
        'character' => 'getCharacter',
        'situation' => 'getSituation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('history', $data ?? [], null);
        $this->setIfExists('source_lang', $data ?? [], null);
        $this->setIfExists('target_lang', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('character', $data ?? [], null);
        $this->setIfExists('situation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ($this->container['source_lang'] === null) {
            $invalidProperties[] = "'source_lang' can't be null";
        }
        if ($this->container['target_lang'] === null) {
            $invalidProperties[] = "'target_lang' can't be null";
        }
        if (!is_null($this->container['level']) && ($this->container['level'] > 255)) {
            $invalidProperties[] = "invalid value for 'level', must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['level']) && ($this->container['level'] < 0)) {
            $invalidProperties[] = "invalid value for 'level', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage(): string
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message message
     *
     * @return $this
     */
    public function setMessage(string $message): static
    {
        if (is_null($message)) {
            throw new InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets history
     *
     * @return \Lingara\Model\TurnEntry[]|null
     */
    public function getHistory(): ?array
    {
        return $this->container['history'];
    }

    /**
     * Sets history
     *
     * @param \Lingara\Model\TurnEntry[]|null $history history
     *
     * @return $this
     */
    public function setHistory(?array $history): static
    {
        if (is_null($history)) {
            throw new InvalidArgumentException('non-nullable history cannot be null');
        }
        $this->container['history'] = $history;

        return $this;
    }

    /**
     * Gets source_lang
     *
     * @return string
     */
    public function getSourceLang(): string
    {
        return $this->container['source_lang'];
    }

    /**
     * Sets source_lang
     *
     * @param string $source_lang source_lang
     *
     * @return $this
     */
    public function setSourceLang(string $source_lang): static
    {
        if (is_null($source_lang)) {
            throw new InvalidArgumentException('non-nullable source_lang cannot be null');
        }
        $this->container['source_lang'] = $source_lang;

        return $this;
    }

    /**
     * Gets target_lang
     *
     * @return string
     */
    public function getTargetLang(): string
    {
        return $this->container['target_lang'];
    }

    /**
     * Sets target_lang
     *
     * @param string $target_lang target_lang
     *
     * @return $this
     */
    public function setTargetLang(string $target_lang): static
    {
        if (is_null($target_lang)) {
            throw new InvalidArgumentException('non-nullable target_lang cannot be null');
        }
        $this->container['target_lang'] = $target_lang;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int|null
     */
    public function getLevel(): ?int
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int|null $level level
     *
     * @return $this
     */
    public function setLevel(?int $level): static
    {
        if (is_null($level)) {
            array_push($this->openAPINullablesSetToNull, 'level');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('level', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($level) && ($level > 255)) {
            throw new InvalidArgumentException('invalid value for $level when calling TutorTurnRequest., must be smaller than or equal to 255.');
        }
        if (!is_null($level) && ($level < 0)) {
            throw new InvalidArgumentException('invalid value for $level when calling TutorTurnRequest., must be bigger than or equal to 0.');
        }

        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets character
     *
     * @return string|null
     */
    public function getCharacter(): ?string
    {
        return $this->container['character'];
    }

    /**
     * Sets character
     *
     * @param string|null $character character
     *
     * @return $this
     */
    public function setCharacter(?string $character): static
    {
        if (is_null($character)) {
            array_push($this->openAPINullablesSetToNull, 'character');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('character', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['character'] = $character;

        return $this;
    }

    /**
     * Gets situation
     *
     * @return string|null
     */
    public function getSituation(): ?string
    {
        return $this->container['situation'];
    }

    /**
     * Sets situation
     *
     * @param string|null $situation situation
     *
     * @return $this
     */
    public function setSituation(?string $situation): static
    {
        if (is_null($situation)) {
            array_push($this->openAPINullablesSetToNull, 'situation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('situation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['situation'] = $situation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


