<?php
/**
 * VersionState
 *
 * PHP version 8.1
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lingara API
 *
 * Generate vocabulary lists and lesson plans, and hold tutor conversations, in the languages Lingara teaches. Each call is paid for by the client that makes it: an `allowance` client spends its owner's allowance, and a `metered` client is billed for its usage.
 *
 * The version of the OpenAPI document: 2026-09-glowing-hoatzin
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lingara\Model;

/**
 * VersionState Class Doc Comment
 *
 * @package  Lingara
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum VersionState: string
{
    case DEVELOPMENT = 'development';

    case SUPPORTED = 'supported';

    case LTS = 'lts';

    case DEPRECATED = 'deprecated';

    case DISCONTINUED = 'discontinued';

    case UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
}


