<?php

// Generated by php/codegen/generate.php from the generator view. DO NOT EDIT.

declare(strict_types=1);

namespace Lingara\Stream\CreateLessonPlanEvent;

/** The `started` event: its payload is `$data`. */
final readonly class Started implements \Lingara\Stream\CreateLessonPlanEvent
{
    // Fully qualified: an event may share its short name with its
    // payload's model (`notice` carries a Notice).
    public function __construct(public \Lingara\Model\PlanStarted $data)
    {
    }
}
